/**
 * 3D Model Showcase — Turntable video-on-hover cards
 * 25 products with static thumbnail + rotating video preview
 *
 * thumb: static hero image (Cloudflare Images / external)
 * videoUrl: turntable rotation video (Cloudflare Stream / external)
 */

// ─── Types ────────────────────────────────────────────────────
export interface Showcase3DModel {
  id: string;
  name: string;
  creator: string;
  creatorAvatar: string;
  likes: number;
  featured?: boolean;
  thumb: string;
  videoUrl: string;
  category: '3d-character' | '3d-environment' | '3d-creature' | '3d-prop' | '3d-vehicle' | '3d-sculpture';
  tags: string[];
  polyCount?: string;
  software?: string;
}

// ─── 25 Showcase 3D Models ───────────────────────────────────
export const SHOWCASE_3D_MODELS: Showcase3DModel[] = [
  // ── Characters ──
  {
    id: '3d-werewolf-beast',
    name: 'Werewolf Beast',
    creator: 'Aristo Kristandyo',
    creatorAvatar: 'https://api.dicebear.com/9.x/adventurer/svg?seed=aristo',
    likes: 36,
    thumb: 'https://imagedelivery.net/eCWooK4EUyalJ6a-Nut5cw/608e43e0-710a-4658-8853-1223939faa00/public',
    videoUrl: 'https://customer-xq04fu0u3xog8ay1.cloudflarestream.com/a2b534c5a2db29ba9d19ef80a062c9f1/downloads/default.mp4',
    category: '3d-character',
    tags: ['character', 'creature', 'fantasy', 'zbrush'],
    polyCount: '2.4M',
    software: 'ZBrush',
  },
  {
    id: '3d-white-knight',
    name: 'White Knight',
    creator: 'Aristo Kristandyo',
    creatorAvatar: 'https://api.dicebear.com/9.x/adventurer/svg?seed=aristo',
    likes: 24,
    featured: true,
    thumb: 'https://imagedelivery.net/eCWooK4EUyalJ6a-Nut5cw/c101ff86-7a72-4536-afca-38811bc75c00/public',
    videoUrl: 'https://customer-xq04fu0u3xog8ay1.cloudflarestream.com/ac78e321ec4edb52ece4bccb67b2bd91/downloads/default.mp4', // TODO: retry video generation (Google Veo rate-limited)
    category: '3d-character',
    tags: ['character', 'knight', 'medieval', 'armor'],
    polyCount: '1.8M',
    software: 'ZBrush + Marvelous',
  },
  {
    id: '3d-gorilla-warrior',
    name: 'Gorilla Warrior',
    creator: 'shing75',
    creatorAvatar: 'https://api.dicebear.com/9.x/adventurer/svg?seed=shing75',
    likes: 74,
    thumb: 'https://imagedelivery.net/eCWooK4EUyalJ6a-Nut5cw/766ad58b-ba24-4b04-4ba4-58b260615a00/public',
    videoUrl: 'https://customer-xq04fu0u3xog8ay1.cloudflarestream.com/301ad6ead0251960681b7a9447b27e9a/downloads/default.mp4',
    category: '3d-character',
    tags: ['character', 'creature', 'steampunk', 'gorilla'],
    polyCount: '3.1M',
    software: 'ZBrush',
  },
  {
    id: '3d-cyber-samurai',
    name: 'Cyber Samurai',
    creator: 'NexGen3D',
    creatorAvatar: 'https://api.dicebear.com/9.x/adventurer/svg?seed=nexgen3d',
    likes: 112,
    featured: true,
    thumb: 'https://imagedelivery.net/eCWooK4EUyalJ6a-Nut5cw/d7a86ebf-5d8b-4210-17da-617b1d236000/public',
    videoUrl: 'https://customer-xq04fu0u3xog8ay1.cloudflarestream.com/430f6b2b993ca7655c9ca167b1f68175/downloads/default.mp4',
    category: '3d-character',
    tags: ['character', 'cyberpunk', 'samurai', 'sci-fi'],
    polyCount: '2.7M',
    software: 'Blender + ZBrush',
  },
  {
    id: '3d-forest-witch',
    name: 'Forest Witch',
    creator: 'Kaesar3d',
    creatorAvatar: 'https://api.dicebear.com/9.x/adventurer/svg?seed=kaesar3d',
    likes: 89,
    thumb: 'https://imagedelivery.net/eCWooK4EUyalJ6a-Nut5cw/bbcfbcbc-8308-4c8a-dd77-85e57a2b4200/public',
    videoUrl: 'https://customer-xq04fu0u3xog8ay1.cloudflarestream.com/0f949400c17df633a31c70f759fb609b/downloads/default.mp4',
    category: '3d-character',
    tags: ['character', 'fantasy', 'witch', 'stylized'],
    polyCount: '1.5M',
    software: 'Blender',
  },
  {
    id: '3d-ronin-ghost',
    name: 'Ronin Ghost',
    creator: 'TakumiArts',
    creatorAvatar: 'https://api.dicebear.com/9.x/adventurer/svg?seed=takumiarts',
    likes: 63,
    thumb: 'https://imagedelivery.net/eCWooK4EUyalJ6a-Nut5cw/9c39991f-cf8f-42e2-932a-e68dfa833c00/public',
    videoUrl: 'https://customer-xq04fu0u3xog8ay1.cloudflarestream.com/f556a1126209cb2dfafe75d3c20a0d31/downloads/default.mp4',
    category: '3d-character',
    tags: ['character', 'japanese', 'ronin', 'ghost'],
    polyCount: '2.2M',
    software: 'ZBrush + Substance',
  },
  {
    id: '3d-mech-pilot',
    name: 'Mech Pilot Girl',
    creator: 'PixelForge',
    creatorAvatar: 'https://api.dicebear.com/9.x/adventurer/svg?seed=pixelforge',
    likes: 45,
    thumb: 'https://imagedelivery.net/eCWooK4EUyalJ6a-Nut5cw/908baacf-7d3c-4ca9-7943-da5605f02600/public',
    videoUrl: 'https://customer-xq04fu0u3xog8ay1.cloudflarestream.com/2e1584045bbc4b23f4f6f61a91569e00/downloads/default.mp4',
    category: '3d-character',
    tags: ['character', 'sci-fi', 'mech', 'anime'],
    polyCount: '1.9M',
    software: 'Blender',
  },
  {
    id: '3d-orc-chieftain',
    name: 'Orc Chieftain',
    creator: 'DarkRealm',
    creatorAvatar: 'https://api.dicebear.com/9.x/adventurer/svg?seed=darkrealm',
    likes: 58,
    thumb: 'https://imagedelivery.net/eCWooK4EUyalJ6a-Nut5cw/9aaf728a-2b78-4572-e247-84211396da00/public',
    videoUrl: 'https://customer-xq04fu0u3xog8ay1.cloudflarestream.com/7307816b06ac6614771e6257aadf52ff/downloads/default.mp4',
    category: '3d-character',
    tags: ['character', 'orc', 'fantasy', 'warrior'],
    polyCount: '2.8M',
    software: 'ZBrush',
  },

  // ── Creatures ──
  {
    id: '3d-dragon-elder',
    name: 'Elder Dragon',
    creator: 'Kaesar3d',
    creatorAvatar: 'https://api.dicebear.com/9.x/adventurer/svg?seed=kaesar3d',
    likes: 51,
    thumb: 'https://imagedelivery.net/eCWooK4EUyalJ6a-Nut5cw/9501ea38-1a3b-4281-fb06-cc510e5a1e00/public',
    videoUrl: 'https://customer-xq04fu0u3xog8ay1.cloudflarestream.com/4e8eeabc3e66ff6188bca77d6e674413/downloads/default.mp4',
    category: '3d-creature',
    tags: ['creature', 'dragon', 'fantasy', 'epic'],
    polyCount: '4.2M',
    software: 'ZBrush',
  },
  {
    id: '3d-phoenix-flame',
    name: 'Phoenix Rising',
    creator: 'MythicArts',
    creatorAvatar: 'https://api.dicebear.com/9.x/adventurer/svg?seed=mythicarts',
    likes: 97,
    featured: true,
    thumb: 'https://imagedelivery.net/eCWooK4EUyalJ6a-Nut5cw/ce12760f-ac53-4fd5-67f9-cefa00d77500/public',
    videoUrl: 'https://customer-xq04fu0u3xog8ay1.cloudflarestream.com/e721c1d47b70c1dfebd077e724e57df1/downloads/default.mp4',
    category: '3d-creature',
    tags: ['creature', 'phoenix', 'fire', 'mythical'],
    polyCount: '3.5M',
    software: 'Houdini + ZBrush',
  },
  {
    id: '3d-deep-sea-leviathan',
    name: 'Deep Sea Leviathan',
    creator: 'OceanDepth',
    creatorAvatar: 'https://api.dicebear.com/9.x/adventurer/svg?seed=oceandepth',
    likes: 42,
    thumb: 'https://imagedelivery.net/eCWooK4EUyalJ6a-Nut5cw/9ea1c168-5a76-44e7-f23d-dbffabc49e00/public',
    videoUrl: 'https://customer-xq04fu0u3xog8ay1.cloudflarestream.com/45391343dd1cf71fc372a3e8d9ffc2a6/downloads/default.mp4',
    category: '3d-creature',
    tags: ['creature', 'sea', 'monster', 'underwater'],
    polyCount: '3.8M',
    software: 'ZBrush + Maya',
  },
  {
    id: '3d-shadow-wolf',
    name: 'Shadow Wolf',
    creator: 'shing75',
    creatorAvatar: 'https://api.dicebear.com/9.x/adventurer/svg?seed=shing75',
    likes: 66,
    thumb: 'https://imagedelivery.net/eCWooK4EUyalJ6a-Nut5cw/1512a6a0-8c18-4b23-fce6-ea6ef17f6a00/public',
    videoUrl: 'https://customer-xq04fu0u3xog8ay1.cloudflarestream.com/4fef249933074e0e306d43a9d183fb3e/downloads/default.mp4',
    category: '3d-creature',
    tags: ['creature', 'wolf', 'dark', 'mystical'],
    polyCount: '2.1M',
    software: 'Blender',
  },

  // ── Environments / Dioramas ──
  {
    id: '3d-teacup-garden',
    name: 'Teacup Garden',
    creator: 'Kaesar3d',
    creatorAvatar: 'https://api.dicebear.com/9.x/adventurer/svg?seed=kaesar3d',
    likes: 51,
    thumb: 'https://imagedelivery.net/eCWooK4EUyalJ6a-Nut5cw/4532fda4-252a-48f6-1203-0d10cab52a00/public',
    videoUrl: 'https://customer-xq04fu0u3xog8ay1.cloudflarestream.com/a136d0afb6616183f40acac003796e80/downloads/default.mp4',
    category: '3d-environment',
    tags: ['environment', 'diorama', 'stylized', 'whimsical'],
    polyCount: '800K',
    software: 'Blender',
  },
  {
    id: '3d-floating-temple',
    name: 'Floating Temple',
    creator: 'SkyBuilder',
    creatorAvatar: 'https://api.dicebear.com/9.x/adventurer/svg?seed=skybuilder',
    likes: 83,
    thumb: 'https://imagedelivery.net/eCWooK4EUyalJ6a-Nut5cw/f9eb78fa-917b-4857-a530-5167932fef00/public',
    videoUrl: 'https://customer-xq04fu0u3xog8ay1.cloudflarestream.com/1e96b4ae0e53ac84e9fc000894ae1f33/downloads/default.mp4', // TODO: retry video generation (Google Veo rate-limited)
    category: '3d-environment',
    tags: ['environment', 'temple', 'floating', 'fantasy'],
    polyCount: '1.2M',
    software: 'Blender + UE5',
  },
  {
    id: '3d-cyberpunk-alley',
    name: 'Neon Alley',
    creator: 'NexGen3D',
    creatorAvatar: 'https://api.dicebear.com/9.x/adventurer/svg?seed=nexgen3d',
    likes: 71,
    thumb: 'https://imagedelivery.net/eCWooK4EUyalJ6a-Nut5cw/0fc65371-b4fa-4ad1-9bc2-21be907e2700/public',
    videoUrl: 'https://customer-xq04fu0u3xog8ay1.cloudflarestream.com/83abc56b3be34057164d2cd5e1ce0e26/downloads/default.mp4',
    category: '3d-environment',
    tags: ['environment', 'cyberpunk', 'neon', 'urban'],
    polyCount: '1.8M',
    software: 'UE5',
  },
  {
    id: '3d-ancient-ruins',
    name: 'Ancient Ruins',
    creator: 'ArchViz_Pro',
    creatorAvatar: 'https://api.dicebear.com/9.x/adventurer/svg?seed=archvizpro',
    likes: 39,
    thumb: 'https://imagedelivery.net/eCWooK4EUyalJ6a-Nut5cw/a51b53af-7a05-4b64-3e54-34420380b700/public',
    videoUrl: 'https://customer-xq04fu0u3xog8ay1.cloudflarestream.com/cad578add00c3d793dbccd9f0dc730bd/downloads/default.mp4',
    category: '3d-environment',
    tags: ['environment', 'ruins', 'ancient', 'overgrown'],
    polyCount: '2.5M',
    software: 'Blender',
  },
  {
    id: '3d-mushroom-village',
    name: 'Mushroom Village',
    creator: 'TinyWorld',
    creatorAvatar: 'https://api.dicebear.com/9.x/adventurer/svg?seed=tinyworld',
    likes: 105,
    featured: true,
    thumb: 'https://imagedelivery.net/eCWooK4EUyalJ6a-Nut5cw/44059897-3101-4f8f-14c5-8fd7707f8700/public',
    videoUrl: 'https://customer-xq04fu0u3xog8ay1.cloudflarestream.com/5c5029182ab79544e0c10470b503a2da/downloads/default.mp4',
    category: '3d-environment',
    tags: ['environment', 'diorama', 'mushroom', 'cute'],
    polyCount: '600K',
    software: 'Blender',
  },

  // ── Props & Items ──
  {
    id: '3d-sci-fi-crate',
    name: 'Sci-Fi Cargo Crate',
    creator: 'Anonymous177384',
    creatorAvatar: 'https://api.dicebear.com/9.x/adventurer/svg?seed=anon177384',
    likes: 28,
    thumb: 'https://imagedelivery.net/eCWooK4EUyalJ6a-Nut5cw/81215bef-808c-404f-2cb9-de95c930a700/public',
    videoUrl: 'https://customer-xq04fu0u3xog8ay1.cloudflarestream.com/4bc006ea5873f6321f619cab9b5a0f10/downloads/default.mp4',
    category: '3d-prop',
    tags: ['prop', 'sci-fi', 'crate', 'game-ready'],
    polyCount: '12K',
    software: 'Blender + Substance',
  },
  {
    id: '3d-enchanted-sword',
    name: 'Enchanted Blade',
    creator: 'ForgeSmith',
    creatorAvatar: 'https://api.dicebear.com/9.x/adventurer/svg?seed=forgesmith',
    likes: 94,
    thumb: 'https://imagedelivery.net/eCWooK4EUyalJ6a-Nut5cw/a43d0fb5-9c09-46b8-c957-8248c8f37100/public',
    videoUrl: 'https://customer-xq04fu0u3xog8ay1.cloudflarestream.com/ccf76903aeb628809338ec86e07c59d6/downloads/default.mp4',
    category: '3d-prop',
    tags: ['prop', 'weapon', 'sword', 'enchanted'],
    polyCount: '45K',
    software: 'Blender',
  },
  {
    id: '3d-steampunk-clock',
    name: 'Steampunk Clock Tower',
    creator: 'GearMaster',
    creatorAvatar: 'https://api.dicebear.com/9.x/adventurer/svg?seed=gearmaster',
    likes: 57,
    thumb: 'https://imagedelivery.net/eCWooK4EUyalJ6a-Nut5cw/b5ea109d-7e71-468f-3e30-784b571e1f00/public',
    videoUrl: 'https://customer-xq04fu0u3xog8ay1.cloudflarestream.com/e51ef74c5e6deddbccb9dd2490f73510/downloads/default.mp4',
    category: '3d-prop',
    tags: ['prop', 'steampunk', 'clock', 'mechanical'],
    polyCount: '350K',
    software: 'Blender + Substance',
  },

  // ── Vehicles ──
  {
    id: '3d-hover-bike',
    name: 'Hover Bike X-7',
    creator: 'VehicleLab',
    creatorAvatar: 'https://api.dicebear.com/9.x/adventurer/svg?seed=vehiclelab',
    likes: 82,
    thumb: 'https://imagedelivery.net/eCWooK4EUyalJ6a-Nut5cw/7c001b7c-8571-4bf8-393c-2f638df76a00/public',
    videoUrl: 'https://customer-xq04fu0u3xog8ay1.cloudflarestream.com/b0bdced376f69b96cc5134ed489f5135/downloads/default.mp4',
    category: '3d-vehicle',
    tags: ['vehicle', 'hover', 'sci-fi', 'futuristic'],
    polyCount: '180K',
    software: 'Blender',
  },
  {
    id: '3d-pirate-ship',
    name: 'Ghost Pirate Ship',
    creator: 'MythicArts',
    creatorAvatar: 'https://api.dicebear.com/9.x/adventurer/svg?seed=mythicarts',
    likes: 48,
    thumb: 'https://imagedelivery.net/eCWooK4EUyalJ6a-Nut5cw/e0550642-c238-4a4c-6bbf-342f2c858300/public',
    videoUrl: 'https://customer-xq04fu0u3xog8ay1.cloudflarestream.com/6cb31f8fcf69fef627d28e379d35b4be/downloads/default.mp4',
    category: '3d-vehicle',
    tags: ['vehicle', 'pirate', 'ghost', 'fantasy'],
    polyCount: '950K',
    software: 'Maya + Substance',
  },

  // ── Sculptures ──
  {
    id: '3d-atlas-titan',
    name: 'Atlas Titan',
    creator: 'Aristo Kristandyo',
    creatorAvatar: 'https://api.dicebear.com/9.x/adventurer/svg?seed=aristo',
    likes: 131,
    featured: true,
    thumb: 'https://imagedelivery.net/eCWooK4EUyalJ6a-Nut5cw/143613f1-db28-4d02-9df6-7c4395136800/public',
    videoUrl: 'https://customer-xq04fu0u3xog8ay1.cloudflarestream.com/45a1c7ef0bbb5e878915f8ec04e46546/downloads/default.mp4',
    category: '3d-sculpture',
    tags: ['sculpture', 'titan', 'mythology', 'classical'],
    polyCount: '5.2M',
    software: 'ZBrush',
  },
  {
    id: '3d-demon-mask',
    name: 'Oni Demon Mask',
    creator: 'TakumiArts',
    creatorAvatar: 'https://api.dicebear.com/9.x/adventurer/svg?seed=takumiarts',
    likes: 77,
    thumb: 'https://imagedelivery.net/eCWooK4EUyalJ6a-Nut5cw/13f5486a-10cd-494b-d12f-c11da70fc000/public',
    videoUrl: 'https://customer-xq04fu0u3xog8ay1.cloudflarestream.com/6bb58616072e9ebde01608d79e65daed/downloads/default.mp4',
    category: '3d-sculpture',
    tags: ['sculpture', 'mask', 'japanese', 'oni'],
    polyCount: '1.1M',
    software: 'ZBrush',
  },
  {
    id: '3d-crystal-golem',
    name: 'Crystal Golem',
    creator: 'DarkRealm',
    creatorAvatar: 'https://api.dicebear.com/9.x/adventurer/svg?seed=darkrealm',
    likes: 55,
    thumb: 'https://imagedelivery.net/eCWooK4EUyalJ6a-Nut5cw/6b5dd0f9-95a0-48e6-5a5b-e484b022ec00/public',
    videoUrl: 'https://customer-xq04fu0u3xog8ay1.cloudflarestream.com/f5dafc160b3d4cddfe3dd21cf651412c/downloads/default.mp4',
    category: '3d-sculpture',
    tags: ['sculpture', 'golem', 'crystal', 'fantasy'],
    polyCount: '2.9M',
    software: 'ZBrush + Blender',
  },
];

// ─── Category labels ─────────────────────────────────────────
export const CATEGORY_3D_LABELS: Record<Showcase3DModel['category'], string> = {
  '3d-character': 'Characters',
  '3d-environment': 'Environments',
  '3d-creature': 'Creatures',
  '3d-prop': 'Props',
  '3d-vehicle': 'Vehicles',
  '3d-sculpture': 'Sculptures',
};
