
import React, { createContext, useContext, useState, useEffect } from 'react';
import { Language } from '../types';

interface LanguageContextType {
  lang: Language;
  setLang: (lang: Language) => void;
  t: (key: string) => string;
}

const translations: Record<Language, Record<string, string>> = {
  en: {
    'nav.browse': 'Market',
    'nav.explore': 'Explore',
    'nav.explorer': 'Explorer',
    'nav.models': 'Models',
    'nav.apps': 'Apps',
    'nav.about': 'About',
    'nav.deploy': 'Contact',
    'nav.login': 'Sign In',
    'nav.lang_settings': 'Language Settings',
    'user.menu.signout': 'Sign Out',
    'user.menu.profile': 'View Profile',
    'user.menu.referral': 'Refer Friends',
    'user.menu.admin': 'Admin Pro Panel',
    'user.menu.favorites': 'Assets Vault',
    'user.menu.usage': 'Usage History',
    'user.menu.settings': 'System Settings',
    'user.menu.support': 'Support Center',
    'user.menu.credits_label': 'Total Credits',
    'policy.title': 'Operating Policy & Terms of Service',
    'policy.subtitle': 'Welcome to Market Skyverses. To ensure a safe, legal, and professional environment, all users must strictly adhere to the following policies. Failure to comply will result in immediate account suspension.',
    'policy.1.title': 'Legal Compliance',
    'policy.1.content': 'Users strictly MUST NOT create, upload, generate, or share content that violates local or international laws. This includes, but is not limited to, child sexual abuse material (CSAM), promotion of terrorism, hate speech, and illegal acts.',
    'policy.2.title': 'Copyright & IP',
    'policy.2.content': 'Respect intellectual property. Do not use copyrighted music, video, or images without proper licensing or permission. Market Skyverses operates a strict repeat infringer policy and respects DMCA takedown requests.',
    'policy.3.title': 'System Integrity',
    'policy.3.content': 'Do not attempt to reverse engineer, hack, or exploit the platform. Using automated bots for rendering, exploiting storage limits, or account sharing is prohibited.',
    'policy.4.title': 'Ethical AI Usage',
    'policy.4.content': 'AI features must NOT be used to create deepfakes of real people without consent, non-consensual sexual content (NCII), or political misinformation. Watermarks indicating AI generation must not be removed.',
    'policy.5.title': 'Prohibited Content List',
    'policy.5.item.1': 'Nudity, pornography, or sexually explicit content.',
    'policy.5.item.2': 'Harassment, bullying, or doxxing.',
    'policy.5.item.3': 'Promotion of self-harm, suicide, or eating disorders.',
    'policy.5.item.4': 'Scams, phishing, or malware distribution.',
    'policy.6.title': 'Termination of Service',
    'policy.6.content': 'Market Skyverses reserves the right to suspend or permanently ban any account found violating these policies without prior notice or refund. Suspicious activities may be reported to relevant authorities.',
    'policy.updates.title': 'Updates to Terms',
    'policy.updates.content': 'Market Skyverses may update these rules at any time. Continued use of the service constitutes acceptance of the modified terms. It is your responsibility to review these policies periodically.',
    'settings.title': 'Settings',
    'settings.tabs.profile': 'Personal Profile',
    'settings.tabs.compute': 'Credits & Compute',
    'settings.tabs.cloud': 'Cloud Storage',
    'settings.tabs.keys': 'Model Keys',
    'settings.tabs.referrals': 'Referrals & Rewards',
    'settings.tabs.security': 'Security & Privacy',
    'settings.tabs.billing': 'Plans & Billing',
    'settings.profile.name': 'Full Name',
    'settings.profile.email': 'Contact Email',
    'settings.profile.username': 'Username',
    'settings.profile.language': 'Interface Language',
    'settings.profile.save': 'Save Changes',
    'settings.profile.verified': 'Verified Member',
    'settings.compute.balance_label': 'Current Balance',
    'settings.compute.topup': 'Topup +',
    'settings.compute.stats': 'Creative Statistics',
    'settings.compute.used_month': 'Used (Month)',
    'settings.compute.last_tx': 'Last Transaction',
    'settings.compute.performance': 'Performance',
    'settings.compute.optimal': 'Optimal',
    'settings.cloud.desc': 'Sync your assets, projects, and videos across all devices. High-speed access for video production.',
    'settings.cloud.usage': 'STORAGE USED',
    'settings.cloud.free': 'Free',
    'settings.cloud.current': 'Current Plan',
    'settings.cloud.upgrade': 'Upgrade',
    'settings.cloud.basic.title': 'Basic',
    'settings.cloud.basic.desc': 'Perfect for starters. Store basic assets and light projects.',
    'settings.cloud.studio.title': 'Studio',
    'settings.cloud.studio.desc': 'For professional editors. High-quality footage and faster rendering.',
    'settings.cloud.cinema.title': 'Cinema',
    'settings.cloud.cinema.desc': 'For Production Houses. 4K/8K storage, team collab and massive vault.',
    'settings.keys.title': 'Model Keys Management',
    'settings.keys.desc': 'Use personal API keys to expand your creation quota.',
    'settings.keys.placeholder': 'Enter key...',
    'settings.keys.save': 'Save Configuration',
    'settings.keys.reset': 'Purge All Keys',
    'settings.keys.byok': 'Security First (BYOK)',
    'settings.keys.byok_desc': 'Your keys are stored locally in your browser and never leave this device.',
    'settings.referrals.desc': 'Invite friends to create together and receive triân Credits.',
    'settings.referrals.total_reward': 'Total Rewards Received',
    'settings.referrals.friends_invited': 'Friends Invited',
    'settings.referrals.active_friends': 'Active companions',
    'settings.referrals.link_label': 'Creation Invitation Gateway',
    'settings.referrals.copy': 'Copy',
    'settings.referrals.copied': 'Copied',
    'settings.referrals.history': 'Companion Log',
    'settings.referrals.table.friend': 'Friend',
    'settings.referrals.table.date': 'Join Date',
    'settings.referrals.table.status': 'Status',
    'settings.referrals.table.reward': 'Reward',
    'settings.security.title': 'Security & Access',
    'settings.security.2fa': 'Two-Factor Authentication (2FA)',
    'settings.security.2fa_desc': 'Enhance account protection with OTP codes.',
    'settings.security.password': 'Access Password',
    'settings.security.password_desc': 'Change your login password.',
    'settings.security.change': 'Change',
    'settings.billing.title': 'Current Subscription',
    'settings.billing.monthly': 'Monthly',
    'settings.billing.expires': 'Your plan will expire on:',
    'settings.billing.renew': 'Renew Now',
    'explorer.title': 'THE EXPLORER.',
    'explorer.subtitle': 'Where AI ideas become reality.',
    'explorer.empty': 'No results found',
    'explorer.retry': 'Try Again',
    'explorer.loading': 'Syncing data...',
    'explorer.filter.label': 'Filter:',
    'explorer.type.all': 'All',
    'explorer.type.text_video': 'Text → Motion',
    'explorer.type.image_video': 'Image → Motion',
    'explorer.type.character': 'Identity Sync',
    'explorer.type.cinematic': 'Cinematic Film',
    'explorer.type.gameplay': 'Game Graphics',
    'explorer.type.game_asset_3d': '3D Entity',
    'explorer.modal.architect': 'Content Architect',
    'explorer.modal.prompt': 'Prompt Script',
    'explorer.modal.copy': 'COPY',
    'explorer.modal.copied': 'COPIED',
    'explorer.modal.specs': 'Technical Specs',
    'explorer.modal.tags': 'Classification & Tags',
    'explorer.modal.resynth_btn': 'RE-SYNTHESIZE IDEA',
    'explorer.modal.studio_btn': 'OPEN IN 3D STUDIO',
    'explorer.modal.motion_btn': 'CREATE MOTION',
    'explorer.modal.download_btn': 'DOWNLOAD ORIGINAL',
    'explorer.modal.upscale_btn': 'UPSCALE (4K)',
    'explorer.modal.edit_btn': 'EDIT (PRO)',
    'explorer.modal.views': 'VIEWS',
    'explorer.modal.3d_preview': '3D_MESH_PREVIEW',
    'explorer.modal.3d_drag': 'Drag to rotate',
    'explorer.modal.3d_interactive': 'Interactive Model',
    'footer.description': 'Leading AI production studio for work and creativity. Skyverses provides productivity optimization tools to help businesses and individuals break through in the digital age.',
    'footer.about_title': 'About Us',
    'footer.team': 'TEAM',
    'footer.ecosystem': 'ECOSYSTEM',
    'footer.library': 'AI LIBRARY',
    'footer.support_title': 'Support & Partnership',
    'footer.contact': 'CONTACT',
    'footer.center': 'CENTER',
    'footer.partners': 'PARTNERS',
    'footer.copyright': '© 2025 SKYVERSES ECOSYSTEM.',
    'footer.version': 'VERSION 1.0.4 BETA',
    'chat.title': 'ASSISTANT',
    'chat.placeholder': 'ASK ME ANYTHING...',
    'chat.welcome': 'I am the AI assistant of Skyverses. For direct support, please contact: support@skyverses.com.',
    'chat.status': 'ONLINE',
    'chat.active': 'STABLE',
    'chat.protocol': 'NODE_042',
    'chat.latency': 'FAST',
    'login.title': 'Welcome to Skyverses',
    'login.subtitle': 'Sign in and continue creating',
    'login.back': 'Back to home',
    'login.google': 'Continue with Google',
    'login.apple': 'Continue with Apple',
    'login.x': 'Continue with X',
    'login.microsoft': 'Continue with Microsoft',
    'login.or': 'or',
    'login.email': 'Continue with Email',
    'login.feature.1': 'Enterprise Game Architecture',
    'login.feature.2': 'Professional Design Clusters',
    'login.feature.3': 'AI-Powered Media Pipeline',
    'login.notice.title': 'Environment Notice',
    'login.notice.desc': 'Google Sign-In is restricted in this sandbox. Falling back to Developer Mode.',
    'booking.title.1': 'Start Your Next',
    'booking.title.2': 'Production Project',
    'booking.intro': 'We are a multidisciplinary production studio specializing in game development, art & design, and AI-powered tools.',
    'booking.partner': 'We work as an outsourced partner for studios, brands, and teams that need production-ready results — not demos.',
    'booking.services.title': 'Our Services',
    'booking.service.1.title': '🎮 Game Development',
    'booking.service.1.desc': 'Full-cycle game development for mobile, PC, and web — from prototypes to production-ready builds.',
    'booking.service.2.title': '🎨 Art & Design',
    'booking.service.2.desc': 'High-quality game art, UI/UX, illustrations, branding, and cinematic visuals for real pipelines.',
    'booking.service.3.title': '🤖 AI Tools & Automation',
    'booking.service.3.desc': 'Custom AI tools to accelerate content creation, automate workflows, and support internal production systems.',
    'booking.process.title': 'How We Work',
    'booking.process.1': 'Discovery & Scope — Align goals, requirements, timeline, and production constraints.',
    'booking.process.2': 'Production & Iteration — Work as an extended team with fast feedback cycles.',
    'booking.process.3': 'Delivery & Support — Production-ready assets, systems, and post-delivery support.',
    'booking.footer.tags': '🌍 Global team · Remote-friendly · NDA-ready · Production-first',
    'booking.form.title': 'Project Inquiry',
    'booking.form.subtitle': 'Tell us about your project. We’ll review and get back within 48 hours.',
    'booking.form.name': 'Full Name',
    'booking.form.company': 'Company / Studio Name',
    'booking.form.email': 'Work Email',
    'booking.form.type': 'Project Type',
    'booking.form.industry': 'Industry',
    'booking.form.budget': 'Estimated Budget',
    'booking.form.timeline': 'Target Timeline',
    'booking.form.desc': 'Describe your project, scope, timeline, and what you’re looking to outsource.',
    'booking.form.submit': 'Start Project Discussion →',
    'booking.form.footer': 'We respect your data. NDA-friendly discussions available upon request.',
    'market.filter.all': 'ALL',
    'market.filter.games': 'GAMES',
    'market.filter.design': 'ART & DESIGN',
    'market.filter.tools': 'AI TOOLS',
    'market.filter.cases': 'CASE STUDIES',
    'market.filter.secondary_all': 'All {0}',
    'market.placeholder.all': 'Explore services, solutions, and case studies…',
    'market.placeholder.games': 'Explore game development services…',
    'market.placeholder.design': 'Explore art & design production…',
    'market.placeholder.tools': 'Explore AI video, image, and automation tools…',
    'market.placeholder.cases': 'Explore real production case studies…',
    'market.search.directive.1': 'Search by market, use case, or solution…',
    'market.search.directive.2': 'Explore real AI case studies by industry',
    'market.search.directive.3': 'Find AI solutions used in production',
    'market.search.directive.4': 'Discover workflows built for real businesses',
    'market.search.directive.5': 'What problem are you solving today?',
    'market.search.directive.6': 'Browse proven AI use cases',
    'market.search.placeholder': 'Search AI products, apps, and systems...',
    'market.search.no_matches': 'No Matches Detected',
    'market.search.retry': 'Refine your system parameters and retry uplink.',
    'market.search.reset': 'Reset System Search',
    'market.status.verified': 'Verified AI Systems',
    'market.status.operational': 'Operational',
    'market.node.active': 'Node_Active',
    'market.btn.specs': 'Initialize Specs',
    'card.btn': 'Explore',
  },
  vi: {
    'nav.browse': 'Thị trường',
    'nav.explore': 'Khám phá',
    'nav.explorer': 'Explorer',
    'nav.models': 'Models',
    'nav.apps': 'Ứng dụng',
    'nav.about': 'Giới thiệu',
    'nav.deploy': 'Liên hệ',
    'nav.login': 'Đăng nhập',
    'nav.lang_settings': 'Cài đặt ngôn ngữ',
    'user.menu.signout': 'Đăng xuất',
    'user.menu.profile': 'Xem hồ sơ',
    'user.menu.referral': 'Giới thiệu bạn bè',
    'user.menu.admin': 'Quản trị Admin Pro',
    'user.menu.favorites': 'Kho lưu trữ',
    'user.menu.usage': 'Lịch sử sử dụng',
    'user.menu.settings': 'Cài đặt hệ thống',
    'user.menu.support': 'Trung tâm hỗ trợ',
    'user.menu.credits_label': 'Tổng Credits',
    'policy.title': 'Chính sách vận hành & Điều khoản dịch vụ',
    'policy.subtitle': 'Chào mừng bạn đến với Market Skyverses. Để đảm bảo môi trường an toàn, hợp pháp và chuyên nghiệp, tất cả người dùng phải tuân thủ nghiêm ngặt các chính sách sau đây. Việc không tuân thủ sẽ dẫn đến đình chỉ tài khoản ngay lập tức.',
    'policy.1.title': 'Tuân thủ Pháp luật',
    'policy.1.content': 'Người dùng tuyệt đối KHÔNG ĐƯỢC tạo, tải lên, tạo ra hoặc chia sẻ nội dung vi phạm pháp luật địa phương hoặc quốc tế. Điều này bao gồm, nhưng không giới hạn ở nội dung lạm dụng tình dục trẻ em (CSAM), quảng bá chủ nghĩa khủng bố, ngôn từ kích động thù địch và các hành vi bất hợp pháp.',
    'policy.2.title': 'Bản quyền & SHTT',
    'policy.2.content': 'Tôn trọng sở hữu trí tuệ. Không sử dụng nhạc, video hoặc hình ảnh có bản quyền mà không có giấy phép hoặc sự cho phép thích hợp. Market Skyverses áp dụng chính sách nghiêm ngặt đối với người vi phạm nhiều lần và tôn trọng các yêu cầu gỡ bỏ theo DMCA.',
    'policy.3.title': 'Toàn vẹn Hệ thống',
    'policy.3.content': 'Không cố gắng thiết kế ngược, hack hoặc khai thác nền tảng. Nghiêm cấm sử dụng bot tự động để render, khai thác giới hạn lưu trữ hoặc chia sẻ tài khoản.',
    'policy.4.title': 'Sử dụng AI có Đạo đức',
    'policy.4.content': 'Các tính năng AI KHÔNG ĐƯỢC sử dụng để tạo deepfake người thật mà không có sự đồng ý, nội dung tình dục không tự nguyện (NCII) hoặc thông tin sai lệch về chính trị. Không được xóa bỏ các hình mờ (watermark) cho biết nội dung được tạo bởi AI.',
    'policy.5.title': 'Danh sách Nội dung Bị cấm',
    'policy.5.item.1': 'Nội dung khỏa thân, khiêu dâm hoặc khiêu dâm rõ ràng.',
    'policy.5.item.2': 'Quấy rối, bắt nạt hoặc doxing.',
    'policy.5.item.3': 'Quảng bá hành vi tự hại, tự tử hoặc rối loạn ăn uống.',
    'policy.5.item.4': 'Lừa đảo, giả mạo hoặc phát tán mã độc.',
    'policy.6.title': 'Chấm dứt Dịch vụ',
    'policy.6.content': 'Market Skyverses bảo lưu quyền đình chỉ hoặc cấm vĩnh viễn bất kỳ tài khoản nào vi phạm các chính sách này mà không cần thông báo trước hoặc hoàn tiền. Các hoạt động đáng ngờ có thể được báo cáo cho các cơ quan chức năng có liên quan.',
    'policy.updates.title': 'Cập nhật Điều khoản',
    'policy.updates.content': 'Market Skyverses có thể cập nhật các quy tắc này bất cứ lúc nào. Việc tiếp tục sử dụng dịch vụ đồng nghĩa với việc chấp nhận các điều khoản đã được sửa đổi. Bạn có trách nhiệm xem lại các chính sách này định kỳ.',
    'settings.title': 'Cài đặt',
    'settings.tabs.profile': 'Hồ sơ cá nhân',
    'settings.tabs.compute': 'Credits & Compute',
    'settings.tabs.cloud': 'Dữ liệu đám mây',
    'settings.tabs.keys': 'Quản lý Model Keys',
    'settings.tabs.referrals': 'Giới thiệu & Thưởng',
    'settings.tabs.security': 'Bảo mật & Quyền',
    'settings.tabs.billing': 'Gói & Thanh toán',
    'settings.profile.name': 'Họ và tên',
    'settings.profile.email': 'Email liên hệ',
    'settings.profile.username': 'Tên người dùng',
    'settings.profile.language': 'Ngôn ngữ giao diện',
    'settings.profile.save': 'Lưu thay đổi',
    'settings.profile.verified': 'Thành viên Verified',
    'settings.compute.balance_label': 'Số dư hiện tại',
    'settings.compute.topup': 'Nạp thêm +',
    'settings.compute.stats': 'Thống kê sáng tạo',
    'settings.compute.used_month': 'Đã dùng (Tháng)',
    'settings.compute.last_tx': 'Giao dịch cuối',
    'settings.compute.performance': 'Hiệu suất',
    'settings.compute.optimal': 'Tối ưu',
    'settings.cloud.desc': 'Đồng bộ hóa tài nguyên, dự án và video của bạn trên mọi thiết bị. Truy cập tốc độ cao cho sản xuất video.',
    'settings.cloud.usage': 'DUNG LƯỢNG ĐÃ DÙNG',
    'settings.cloud.free': 'Miễn phí',
    'settings.cloud.current': 'Gói hiện tại',
    'settings.cloud.upgrade': 'Nâng cấp',
    'settings.cloud.basic.title': 'Cơ bản',
    'settings.cloud.basic.desc': 'Phù hợp cho người mới. Lưu trữ tài nguyên cơ bản và dự án nhẹ.',
    'settings.cloud.studio.title': 'Studio',
    'settings.cloud.studio.desc': 'Dành cho editor chuyên nghiệp. Footage chất lượng cao và render nhanh hơn.',
    'settings.cloud.cinema.title': 'Cinema',
    'settings.cloud.cinema.desc': 'Dành cho Production House. Lưu trữ 4K/8K, làm việc nhóm và kho lưu trữ khổng lồ.',
    'settings.keys.title': 'Quản lý Model Keys',
    'settings.keys.desc': 'Sử dụng API Key cá nhân để mở rộng hạn ngạch sáng tạo.',
    'settings.keys.placeholder': 'Nhập key...',
    'settings.keys.save': 'Lưu cấu hình',
    'settings.keys.reset': 'Xóa toàn bộ Key',
    'settings.keys.byok': 'Bảo mật ưu tiên (BYOK)',
    'settings.keys.byok_desc': 'Key của bạn được lưu trữ an toàn trong trình duyệt và không bao giờ rời khỏi thiết bị này.',
    'settings.referrals.desc': 'Mời bạn bè cùng sáng tạo và nhận thêm Credits triân.',
    'settings.referrals.total_reward': 'Tổng thưởng nhận được',
    'settings.referrals.friends_invited': 'Bạn bè đã mời',
    'settings.referrals.active_friends': 'Đang cùng đồng hành',
    'settings.referrals.link_label': 'Cửa ngõ mời gọi sáng tạo',
    'settings.referrals.copy': 'Sao chép',
    'settings.referrals.copied': 'Đã chép',
    'settings.referrals.history': 'Nhật ký đồng hành',
    'settings.referrals.table.friend': 'Bạn bè',
    'settings.referrals.table.date': 'Ngày tham gia',
    'settings.referrals.table.status': 'Trạng thái',
    'settings.referrals.table.reward': 'Phần thưởng',
    'settings.security.title': 'Bảo mật & Truy cập',
    'settings.security.2fa': 'Xác thực 2 lớp (2FA)',
    'settings.security.2fa_desc': 'Tăng cường bảo vệ tài khoản bằng mã OTP.',
    'settings.security.password': 'Mật khẩu truy cập',
    'settings.security.password_desc': 'Thay đổi mật khẩu đăng nhập của bạn.',
    'settings.security.change': 'Thay đổi',
    'settings.billing.title': 'Gói tài khoản hiện tại',
    'settings.billing.monthly': 'Hàng tháng',
    'settings.billing.expires': 'Gói của bạn sẽ hết hạn vào:',
    'settings.billing.renew': 'Gia hạn ngay',
    'explorer.title': 'THE EXPLORER.',
    'explorer.subtitle': 'Nơi ý tưởng AI trở thành thực tế.',
    'explorer.empty': 'Không tìm thấy kết quả',
    'explorer.retry': 'Thử lại',
    'explorer.loading': 'Đang đồng bộ dữ liệu...',
    'explorer.filter.label': 'Bộ lọc:',
    'explorer.type.all': 'Tất cả',
    'explorer.type.text_video': 'Chữ → Chuyển động',
    'explorer.type.image_video': 'Ảnh → Chuyển động',
    'explorer.type.character': 'Đồng bộ định danh',
    'explorer.type.cinematic': 'Phim điện ảnh',
    'explorer.type.gameplay': 'Đồ họa Game',
    'explorer.type.game_asset_3d': 'Thực thể 3D',
    'explorer.modal.architect': 'Kiến trúc sư nội dung',
    'explorer.modal.prompt': 'Kịch bản (Prompt)',
    'explorer.modal.copy': 'SAO CHÉP',
    'explorer.modal.copied': 'ĐÃ SAO CHÉP',
    'explorer.modal.specs': 'Thông số kĩ thuật',
    'explorer.modal.tags': 'Phân loại & Thẻ',
    'explorer.modal.resynth_btn': 'TÁI TỔNG HỢP Ý TƯỞNG',
    'explorer.modal.studio_btn': 'MỞ TRONG 3D STUDIO',
    'explorer.modal.motion_btn': 'TẠO CHUYỂN ĐỘNG',
    'explorer.modal.download_btn': 'TẢI XUỐNG GỐC',
    'explorer.modal.upscale_btn': 'NÂNG CẤP (4K)',
    'explorer.modal.edit_btn': 'CHỈNH SỬA (PRO)',
    'explorer.modal.views': 'LƯỢT XEM',
    'explorer.modal.3d_preview': 'XEM_TRƯỚC_3D',
    'explorer.modal.3d_drag': 'Kéo để xoay',
    'explorer.modal.3d_interactive': 'Mô hình tương tác',
    'footer.description': 'Studio sản xuất AI hàng đầu cho công việc và sáng tạo. Skyverses cung cấp các công cụ tối ưu năng suất, giúp doanh nghiệp và cá nhân bứt phá trong kỷ nguyên số.',
    'footer.about_title': 'Về chúng tôi',
    'footer.team': 'ĐỘI NGŨ',
    'footer.ecosystem': 'HỆ SINH THÁI',
    'footer.library': 'THƯ VIỆN AI',
    'footer.support_title': 'Hỗ trợ & Hợp tác',
    'footer.contact': 'LIÊN HỆ',
    'footer.center': 'TRUNG TÂM',
    'footer.partners': 'ĐỐI TÁC',
    'footer.copyright': '© 2025 HỆ SINH THÁI SKYVERSES.',
    'footer.version': 'PHIÊN BẢN 1.0.4 BETA',
    'chat.title': 'TRỢ LÝ',
    'chat.placeholder': 'HỎI BẤT CỨ ĐIỀU GÌ...',
    'chat.welcome': 'Tôi là trợ lý AI của Skyverses. Để được hỗ trợ trực tiếp, vui lòng liên hệ: support@skyverses.com.',
    'chat.status': 'TRỰC TUYẾN',
    'chat.active': 'ỔN ĐỊNH',
    'chat.protocol': 'NODE_042',
    'chat.latency': 'NHANH',
    'login.title': 'Chào mừng đến với Skyverses',
    'login.subtitle': 'Đăng nhập và tiếp tục sáng tạo',
    'login.back': 'Quay lại trang chủ',
    'login.google': 'Tiếp tục với Google',
    'login.apple': 'Tiếp tục với Apple',
    'login.x': 'Tiếp tục với X',
    'login.microsoft': 'Tiếp tục với Microsoft',
    'login.or': 'hoặc',
    'login.email': 'Tiếp tục với Email',
    'login.feature.1': 'Kiến trúc Game Doanh nghiệp',
    'login.feature.2': 'Cụm thiết kế chuyên nghiệp',
    'login.feature.3': 'Luồng truyền thông AI',
    'login.notice.title': 'Thông báo môi trường',
    'login.notice.desc': 'Đăng nhập Google bị giới hạn trong sandbox này. Đang chuyển sang Chế độ Nhà phát triển.',
    'booking.title.1': 'Bắt đầu Dự án',
    'booking.title.2': 'Sản xuất Tiếp theo',
    'booking.intro': 'Chúng tôi là studio sản xuất đa ngành chuyên về phát triển game, nghệ thuật & thiết kế và các công cụ hỗ trợ bởi AI.',
    'booking.partner': 'Chúng tôi vận hành như một đối tác outsource cho các studio, thương hiệu và đội ngũ cần thực tế — không chỉ là bản mẫu.',
    'booking.services.title': 'Dịch vụ của chúng tôi',
    'booking.service.1.title': '🎮 Phát triển Game',
    'booking.service.1.desc': 'Phát triển game toàn kỳ cho mobile, PC và web — từ bản mẫu (prototype) đến các bản build sẵn sàng phát hành.',
    'booking.service.2.title': '🎨 Nghệ thuật & Thiết kế',
    'booking.service.2.desc': 'Game art chất lượng cao, UI/UX, minh họa, thương hiệu và hình ảnh điện ảnh cho các dây chuyền sản xuất thực tế.',
    'booking.service.3.title': '🤖 Công cụ AI & Tự động hóa',
    'booking.service.3.desc': 'Công cụ AI tùy chỉnh giúp tăng tốc tạo nội dung, tự động hóa quy trình và hỗ trợ sản xuất nội bộ.',
    'booking.process.title': 'Cách chúng tôi làm việc',
    'booking.process.1': 'Khám phá & Xác định quy mô — Thống nhất mục tiêu, yêu cầu, tiến độ và ràng buộc.',
    'booking.process.2': 'Sản xuất & Cải tiến — Làm việc như một đội ngũ mở rộng với phản hồi nhanh chóng.',
    'booking.process.3': 'Bàn giao & Hỗ trợ — Tài sản sẵn sàng sử dụng và hỗ trợ sau bàn giao.',
    'booking.footer.tags': '🌍 Đội ngũ toàn cầu · Làm việc từ xa · Sẵn sàng NDA · Ưu tiên sản xuất',
    'booking.form.title': 'Yêu cầu Dự án',
    'booking.form.subtitle': 'Hãy cho chúng tôi biết về dự án của bạn. Chúng tôi sẽ phản hồi trong vòng 48 giờ.',
    'booking.form.name': 'Họ và Tên',
    'booking.form.company': 'Tên Công ty / Studio',
    'booking.form.email': 'Email Công việc',
    'booking.form.type': 'Loại hình dự án',
    'booking.form.industry': 'Lĩnh vực',
    'booking.form.budget': 'Ngân sách dự kiến',
    'booking.form.timeline': 'Thời gian mục tiêu',
    'booking.form.desc': 'Mô tả dự án, phạm vi, thời gian và những gì bạn đang tìm kiếm.',
    'booking.form.submit': 'Bắt đầu thảo luận dự án →',
    'booking.form.footer': 'Chúng tôi tôn trọng dữ liệu của bạn. Sẵn sàng ký NDA theo yêu cầu.',
    'market.filter.all': 'TẤT CẢ',
    'market.filter.games': 'TRÒ CHƠI',
    'market.filter.design': 'NGHỆ THUẬT & DESIGN',
    'market.filter.tools': 'CÔNG CỤ AI',
    'market.filter.cases': 'CASE STUDIES',
    'market.filter.secondary_all': 'Tất cả {0}',
    'market.placeholder.all': 'Khám phá dịch vụ, giải pháp và case study…',
    'market.placeholder.games': 'Khám phá dịch vụ phát triển trò chơi…',
    'market.placeholder.design': 'Khám phá sản xuất nghệ thuật & thiết kế…',
    'market.placeholder.tools': 'Khám phá công cụ video, hình ảnh và tự động hóa AI…',
    'market.placeholder.cases': 'Khám phá các case study sản xuất thực tế…',
    'market.search.directive.1': 'Tìm kiếm theo thị trường, trường hợp sử dụng hoặc giải pháp...',
    'market.search.directive.2': 'Khám phá case study AI thực tế theo từng ngành hàng',
    'market.search.directive.3': 'Tìm giải pháp AI đang vận hành thực tế',
    'market.search.directive.4': 'Khám phá quy trình AI cho doanh nghiệp thực thụ',
    'market.search.directive.5': 'Vấn đề bạn cần giải quyết hôm nay là gì?',
    'market.search.directive.6': 'Duyệt các trường hợp sử dụng AI đã được chứng minh',
    'market.search.placeholder': 'Tìm kiếm sản phẩm, ứng dụng và hệ thống AI...',
    'market.search.no_matches': 'Không tìm thấy kết quả',
    'market.search.retry': 'Vui lòng điều chỉnh thông số và thử lại.',
    'market.search.reset': 'Thiết lập lại tìm kiếm',
    'market.status.verified': 'Hệ thống AI đã xác minh',
    'market.status.operational': 'Sẵn sàng',
    'market.node.active': 'Node_Hoạt_động',
    'market.btn.specs': 'Thông số kỹ thuật',
    'card.btn': 'Khám phá',
  },
  ko: {
    'nav.browse': '마켓',
    'nav.explore': '탐색',
    'nav.explorer': '탐색기',
    'nav.models': '모델',
    'nav.apps': '앱',
    'nav.about': '소개',
    'nav.deploy': '문의하기',
    'nav.login': '로그인',
    'nav.lang_settings': '언어 설정',
    'user.menu.signout': '로그아웃',
    'user.menu.profile': '프로필 보기',
    'user.menu.referral': '친구 추천',
    'user.menu.admin': '관리자 패널',
    'user.menu.favorites': '자산 보관함',
    'user.menu.usage': '사용 기록',
    'user.menu.settings': '시스템 설정',
    'user.menu.support': '고객 센터',
    'user.menu.credits_label': '총 크레딧',
    'policy.title': '운영 정책 및 서비스 약관',
    'policy.subtitle': 'Market Skyverses에 오신 것을 환영합니다. 안전하고 합법적이며 전문적인 환경을 보장하기 위해 모든 사용자는 다음 정책을 엄격히 준수해야 합니다. 준수하지 않을 경우 즉시 계정이 정지됩니다.',
    'settings.title': '설정',
    'settings.tabs.profile': '개인 프로필',
    'settings.tabs.compute': '크레딧 및 컴퓨팅',
    'settings.tabs.cloud': '클라우드 저장소',
    'settings.tabs.keys': '모델 키 관리',
    'settings.tabs.referrals': '추천 및 보상',
    'settings.tabs.security': '보안 및 개인 정보',
    'settings.tabs.billing': '플랜 및 결제',
    'settings.profile.name': '전체 이름',
    'settings.profile.email': '연락처 이메일',
    'settings.profile.username': '사용자 이름',
    'settings.profile.language': '인터페이스 언어',
    'settings.profile.save': '변경 사항 저장',
    'settings.profile.verified': '인증된 회원',
    'settings.compute.balance_label': '현재 잔액',
    'settings.compute.topup': '충전 +',
    'settings.compute.stats': '창의적 통계',
    'settings.compute.used_month': '사용됨 (월)',
    'settings.compute.last_tx': '마지막 거래',
    'settings.compute.performance': '성능',
    'settings.compute.optimal': '최적',
    'settings.cloud.desc': '모든 장치에서 자산, 프로젝트 및 비디오를 동기화하십시오. 비디오 제작을 위한 고속 액세스.',
    'settings.cloud.usage': '사용된 저장 공간',
    'settings.cloud.free': '무료',
    'settings.cloud.current': '현재 플랜',
    'settings.cloud.upgrade': '업그레이드',
    'settings.cloud.basic.title': '기본',
    'settings.cloud.basic.desc': '초보자에게 적합합니다. 기본 자산과 가벼운 프로젝트를 저장하십시오.',
    'settings.cloud.studio.title': '스튜디오',
    'settings.cloud.studio.desc': '전문 편집자용. 고품질 푸티지 및 더 빠른 렌더링.',
    'settings.cloud.cinema.title': '시네마',
    'settings.cloud.cinema.desc': '프로덕션 하우스용. 4K/8K 저장 공간, 팀 협업 및 대규모 보관함.',
    'settings.keys.title': '모델 키 관리',
    'settings.keys.desc': '개인 API 키를 사용하여 생성 할당량을 확장하십시오.',
    'settings.keys.placeholder': '키 입력...',
    'settings.keys.save': '구성 저장',
    'settings.keys.reset': '모든 키 삭제',
    'settings.keys.byok': '보안 우선 (BYOK)',
    'settings.keys.byok_desc': '귀하의 키는 브라우저에 로컬로 저장되며 이 장치를 절대 떠나지 않습니다.',
    'settings.referrals.desc': '친구를 초대하여 함께 만들고 Credits 보상을 받으세요.',
    'settings.referrals.total_reward': '총 받은 보상',
    'settings.referrals.friends_invited': '초대된 친구',
    'settings.referrals.active_friends': '함께 활동 중',
    'settings.referrals.link_label': '창작 초대 게이트웨이',
    'settings.referrals.copy': '복사',
    'settings.referrals.copied': '복사됨',
    'settings.referrals.history': '동반 로그',
    'settings.referrals.table.friend': '친구',
    'settings.referrals.table.date': '가입 날짜',
    'settings.referrals.table.status': '상태',
    'settings.referrals.table.reward': '보상',
    'settings.security.title': '보안 및 액세스',
    'settings.security.2fa': '2단계 인증 (2FA)',
    'settings.security.2fa_desc': 'OTP 코드로 계정 보호를 강화하십시오.',
    'settings.security.password': '액세스 비밀번호',
    'settings.security.password_desc': '로그인 비밀번호를 변경하십시오.',
    'settings.security.change': '변경',
    'settings.billing.title': '현재 구독',
    'settings.billing.monthly': '매월',
    'settings.billing.expires': '플랜 만료일:',
    'settings.billing.renew': '지금 갱신',
    'explorer.title': 'NEURAL EXPLORER',
    'explorer.subtitle': 'AI 아이디어가 현실이 되는 곳.',
    'explorer.empty': '결과가 없습니다',
    'explorer.retry': '다시 시도',
    'explorer.loading': '데이터 동기화 중...',
    'explorer.filter.label': '필터:',
    'explorer.type.all': '전체',
    'explorer.type.text_video': '텍스트 → 모션',
    'explorer.type.image_video': '이미지 → 모션',
    'explorer.type.character': 'ID 동기화',
    'explorer.type.cinematic': '시네마틱 필름',
    'explorer.type.gameplay': '게임 그래픽',
    'explorer.type.game_asset_3d': '3D 엔티티',
    'explorer.modal.architect': '콘텐츠 아키텍트',
    'explorer.modal.prompt': '프롬프트 스크립트',
    'explorer.modal.copy': '복사',
    'explorer.modal.copied': '복사됨',
    'explorer.modal.specs': '기술 사양',
    'explorer.modal.tags': '분류 및 태그',
    'explorer.modal.resynth_btn': '아이디어 재합성',
    'explorer.modal.studio_btn': '3D 스튜디오에서 열기',
    'explorer.modal.motion_btn': '모션 생성',
    'explorer.modal.download_btn': '원본 다운로드',
    'explorer.modal.upscale_btn': '업스케일 (4K)',
    'explorer.modal.edit_btn': '편집 (PRO)',
    'explorer.modal.views': '조회수',
    'explorer.modal.3d_preview': '3D_메쉬_미리보기',
    'explorer.modal.3d_drag': '드래그하여 회전',
    'explorer.modal.3d_interactive': '대화형 모델',
    'footer.description': '업무와 창의성을 위한 최고의 AI 제작 스튜디오입니다. Skyverses원은 비즈니스와 개인이 디지털 시대에 돌파구를 찾을 수 있도록 생산성 최적화 도구를 제공합니다.',
    'footer.about_title': '회사 소개',
    'footer.team': '팀',
    'footer.ecosystem': '에코시스템',
    'footer.library': 'AI 라이브러리',
    'footer.support_title': '지원 및 파트너십',
    'footer.contact': '문의하기',
    'footer.center': '센터',
    'footer.partners': '파트너',
    'footer.copyright': '© 2025 SKYVERSES 에코시스템.',
    'footer.version': '버전 1.0.4 베타',
    'chat.title': '어시스턴트',
    'chat.placeholder': '무엇이든 물어보세요...',
    'chat.welcome': '저는 Skyverses의 AI 어시스턴트입니다. 직접 지원이 필요한 경우 support@skyverses.com으로 문의하세요.',
    'chat.status': '온라인',
    'chat.active': '안정적',
    'chat.protocol': 'NODE_042',
    'chat.latency': '빠름',
    'login.title': 'Skyverses에 오신 것을 환영합니다',
    'login.subtitle': '로그인하고 계속 창작하세요',
    'login.back': '홈으로 돌아가기',
    'login.google': 'Google로 계속하기',
    'login.apple': 'Apple로 계속하기',
    'login.x': 'X로 계속하기',
    'login.microsoft': 'Microsoft로 계속하기',
    'login.or': '또는',
    'login.email': '이메일로 계속하기',
    'login.feature.1': '엔터프라이즈 게임 아키텍처',
    'login.feature.2': '전문 디자인 클러스터',
    'login.feature.3': 'AI 기반 미디어 파이프라인',
    'login.notice.title': '환경 알림',
    'login.notice.desc': '이 샌드박스에서는 Google 로그인이 제한됩니다. 개발자 모드로 전환합니다.',
    'booking.title.1': '다음 생산 프로젝트',
    'booking.title.2': '시작하기',
    'booking.intro': '우리는 게임 개발, 예술 및 디자인, AI 기반 도구를 전문으로 하는 다학문 생산 스튜디오입니다.',
    'booking.partner': '데모가 아닌 실제 생산 준비가 된 결과가 필요한 스튜디오, 브랜드 및 팀을 위한 아웃소싱 파트너로 일합니다.',
    'booking.services.title': '우리의 서비스',
    'booking.service.1.title': '🎮 게임 개발',
    'booking.service.1.desc': '프로토타입에서 생산 준비 완료된 빌드까지 모바일, PC 및 웹을 위한 전체 사이클 게임 개발.',
    'booking.service.2.title': '🎨 예술 및 디자인',
    'booking.service.2.desc': '실제 파이프라인을 위한 고품질 게임 아트, UI/UX, 일러스트레이션, 브랜딩 및 시네마틱 비주얼.',
    'booking.service.3.title': '🤖 AI 도구 및 자동화',
    'booking.service.3.desc': '콘텐츠 제작 속도를 높이고 워크플로우를 자동화하며 내부 생산 시스템을 지원하는 맞춤형 AI 도구.',
    'booking.process.title': '우리의 작업 방식',
    'booking.process.1': '발견 및 범위 — 목표, 요구 사항, 타임라인 및 생산 제약 조건을 정렬합니다.',
    'booking.process.2': '생산 및 반복 — 빠른 피드백 주기를 가진 확장 팀으로 작업합니다.',
    'booking.process.3': '배송 및 지원 — 생산 준비 완료된 자산, 시스템 및 배송 후 지원.',
    'booking.footer.tags': '🌍 글로벌 팀 · 원격 근무 가능 · NDA 준비 · 생산 우선',
    'booking.form.title': '프로젝트 문의',
    'booking.form.subtitle': '프로젝트에 대해 알려주세요. 48시간 이내에 검토하여 연락드리겠습니다.',
    'booking.form.name': '이름',
    'booking.form.company': '회사 / 스튜디오 이름',
    'booking.form.email': '회사 이메일',
    'booking.form.type': '프로젝트 유형',
    'booking.form.industry': '산업',
    'booking.form.budget': '예상 예산',
    'booking.form.timeline': '목표 타임라인',
    'booking.form.desc': '프로젝트, 범위, 타임라인 및 아웃소싱하려는 항목에 대해 설명해 주세요.',
    'booking.form.submit': '프로젝트 논의 시작 →',
    'booking.form.footer': '우리는 귀하의 데이터를 존중합니다. 요청 시 NDA 체결 논의가 가능합니다.',
    'market.filter.all': '전체',
    'market.filter.games': '게임',
    'market.filter.design': '예술 및 디자인',
    'market.filter.tools': 'AI 도구',
    'market.filter.cases': '사례 연구',
    'market.filter.secondary_all': '모든 {0}',
    'market.placeholder.all': '서비스, 솔루션 및 사례 연구 탐색…',
    'market.placeholder.games': '게임 개발 서비스 탐색…',
    'market.placeholder.design': '예술 및 디자인 제작 탐색…',
    'market.placeholder.tools': 'AI 비디오, 이미지 및 자동화 도구 탐색…',
    'market.placeholder.cases': '실제 프로덕션 사례 연구 탐색…',
    'market.search.directive.1': '시장, 유스케이스 또는 솔루션별로 검색…',
    'market.search.directive.2': '산업별 실제 AI 사례 연구 탐색',
    'market.search.directive.3': '실제 운영 중인 AI 솔루션 찾기',
    'market.search.directive.4': '실제 비즈니스를 위해 구축된 워크플로우 발견',
    'market.search.directive.5': '오늘 해결하고자 하는 문제는 무엇인가요?',
    'market.search.directive.6': '검증된 AI 유스케이스 둘러보기',
    'market.search.placeholder': 'AI 제품, 앱 및 시스템 검색...',
    'market.search.no_matches': '일치하는 결과 없음',
    'market.search.retry': '시스템 매개변수를 조정하고 다시 시도하십시오.',
    'market.search.reset': '시스템 검색 초기화',
    'market.status.verified': '검증된 AI 시스템',
    'market.status.operational': '운영 중',
    'market.node.active': '노드_활성',
    'market.btn.specs': '사양 초기화',
    'card.btn': '탐색',
  },
  ja: {
    'nav.browse': 'マーケット',
    'nav.explore': '探索',
    'nav.explorer': 'エクスプローラー',
    'nav.models': 'モデル',
    'nav.apps': 'アプリ',
    'nav.about': '会社概要',
    'nav.deploy': 'お問い合わせ',
    'nav.login': 'ログイン',
    'nav.lang_settings': '言語設定',
    'user.menu.signout': 'ログアウト',
    'user.menu.profile': 'プロフィールを表示',
    'user.menu.referral': '友達を招待',
    'user.menu.admin': '管理パネル',
    'user.menu.favorites': 'アセット保管庫',
    'user.menu.usage': '利用履歴',
    'user.menu.settings': 'システム設定',
    'user.menu.support': 'サポートセンター',
    'user.menu.credits_label': '合計クレジット',
    'policy.title': '運用ポリシーおよび利用規約',
    'policy.subtitle': 'Market Skyversesへようこそ。安全で合法的かつ専門的な環境を確保するため、すべてのユーザーは以下のポリシーを厳守する必要があります。遵守しない場合、直ちにアカウントが停止されます。',
    'settings.title': '設定',
    'settings.tabs.profile': 'プロフィール',
    'settings.tabs.compute': 'クレジットと計算',
    'settings.tabs.cloud': 'クラウドストレージ',
    'settings.tabs.keys': 'モデルキーの管理',
    'settings.tabs.referrals': '紹介と報酬',
    'settings.tabs.security': 'セキュリティとプライバシー',
    'settings.tabs.billing': 'プラン và 請求',
    'settings.profile.name': '氏名',
    'settings.profile.email': '連絡先メールアドレス',
    'settings.profile.username': 'ユーザー名',
    'settings.profile.language': '表示言語',
    'settings.profile.save': '変更を保存',
    'settings.profile.verified': '認証済みメンバー',
    'settings.compute.balance_label': '現在の残高',
    'settings.compute.topup': 'チャージ +',
    'settings.compute.stats': 'クリエイティブ統計',
    'settings.compute.used_month': '利用量 (月)',
    'settings.compute.last_tx': '最終取引',
    'settings.compute.performance': 'パフォーマンス',
    'settings.compute.optimal': '最適',
    'settings.cloud.desc': 'すべてのアセット、プロジェクト、ビデオをデバイス間で同期します。ビデオ制作のための高速アクセス。',
    'settings.cloud.usage': '使用済みストレージ',
    'settings.cloud.free': '無料',
    'settings.cloud.current': '現在のプラン',
    'settings.cloud.upgrade': 'アップグレード',
    'settings.cloud.basic.title': 'ベーシック',
    'settings.cloud.basic.desc': '初心者に最適です。基本的なアセットと軽いプロジェクトを保存します。',
    'settings.cloud.studio.title': 'スタジオ',
    'settings.cloud.studio.desc': 'プロの編集者向け。高品質の映像 và より高速なレンダリング。',
    'settings.cloud.cinema.title': 'シネマ',
    'settings.cloud.cinema.desc': '制作会社向け。4K/8Kストレージ、チームコラボレーション、大規模な保管庫。',
    'settings.keys.title': 'モデルキーの管理',
    'settings.keys.desc': '個人の API キーを使用して、作成クォータを拡張します。',
    'settings.keys.placeholder': 'キーを入力...',
    'settings.keys.save': '構成を保存',
    'settings.keys.reset': 'すべてのキーを削除',
    'settings.keys.byok': 'セキュリティ第一 (BYOK)',
    'settings.keys.byok_desc': 'キーはブラウザにローカルに保存され、このデバイスから外部に出ることはありません。',
    'settings.referrals.desc': '友達を招待して一緒に作成し、Credits報酬を受け取りましょう.',
    'settings.referrals.total_reward': '受け取った合計報酬',
    'settings.referrals.friends_invited': '招待された友達',
    'settings.referrals.active_friends': '一緒に活動中',
    'settings.referrals.link_label': '創作招待ゲートウェイ',
    'settings.referrals.copy': 'コピー',
    'settings.referrals.copied': 'コピー済み',
    'settings.referrals.history': '同伴ログ',
    'settings.referrals.table.friend': '友達',
    'settings.referrals.table.date': '参加日',
    'settings.referrals.table.status': 'ステータス',
    'settings.referrals.table.reward': '報酬',
    'settings.security.title': 'セキュリティとアクセス',
    'settings.security.2fa': '2要素認証 (2FA)',
    'settings.security.2fa_desc': 'OTPコードでアカウント保護を強化します。',
    'settings.security.password': 'アクセスパスワード',
    'settings.security.password_desc': 'ログインパスワードを変更します。',
    'settings.security.change': '変更',
    'settings.billing.title': '現在のサブスクリプション',
    'settings.billing.monthly': '毎月',
    'settings.billing.expires': 'プランの有効期限:',
    'settings.billing.renew': '今すぐ更新',
    'explorer.title': 'NEURAL EXPLORER',
    'explorer.subtitle': 'AIアイデアが現実になる場所。',
    'explorer.empty': '結果が見つかりません',
    'explorer.retry': '再試行',
    'explorer.loading': 'データを同期中...',
    'explorer.filter.label': 'フィルター:',
    'explorer.type.all': 'すべて',
    'explorer.type.text_video': 'テキスト → モーション',
    'explorer.type.image_video': '画像 → モーション',
    'explorer.type.character': 'ID同期',
    'explorer.type.cinematic': 'シネマティックフィルム',
    'explorer.type.gameplay': 'ゲームグラフィックス',
    'explorer.type.game_asset_3d': '3Dエンティティ',
    'explorer.modal.architect': 'コンテンツ・アーキテクト',
    'explorer.modal.prompt': 'プロンプト・スクリプト',
    'explorer.modal.copy': 'コピー',
    'explorer.modal.copied': 'コピー済み',
    'explorer.modal.specs': '技術仕様',
    'explorer.modal.tags': '分類とタグ',
    'explorer.modal.resynth_btn': 'アイデアを再合成',
    'explorer.modal.studio_btn': '3Dスタジオで開く',
    'explorer.modal.motion_btn': 'モーション作成',
    'explorer.modal.download_btn': 'オリジナルをダウンロード',
    'explorer.modal.upscale_btn': 'アップスケール (4K)',
    'explorer.modal.edit_btn': '編集 (PRO)',
    'explorer.modal.views': '再生回数',
    'explorer.modal.3d_preview': '3D_メッシュ_プレビュー',
    'explorer.modal.3d_drag': 'ドラッグして回転',
    'explorer.modal.3d_interactive': '大話型モデル',
    'footer.description': '仕事と創造性のための主要なAI制作スタジオ。 Skyversesは、企業や個人がデジタル時代を切り開くための生産性最適化ツールを提供します。',
    'footer.about_title': '会社概要',
    'footer.team': 'チーム',
    'footer.ecosystem': 'エコシステム',
    'footer.library': 'AIライブラリ',
    'footer.support_title': 'サポート & パートナーシップ',
    'footer.contact': 'お問い合わせ',
    'footer.center': 'センター',
    'footer.partners': 'パートナー',
    'footer.copyright': '© 2025 SKYVERSES エコシステム.',
    'footer.version': 'バージョン 1.0.4 ベータ',
    'chat.title': 'アシスタント',
    'chat.placeholder': '何でも聞いてください...',
    'chat.welcome': '私は Skyverses の AI アシスタントです。直接のサポートが必要な場合は、support@skyverses.com までご連絡ください。',
    'chat.status': 'オンライン',
    'chat.active': '安定',
    'chat.protocol': 'NODE_042',
    'chat.latency': '高速',
    'login.title': 'Skyversesへようこそ',
    'login.subtitle': 'ログインして作成を続行する',
    'login.back': 'ホームに戻る',
    'login.google': 'Googleで続行',
    'login.apple': 'Appleで続行',
    'login.x': 'Xで続行',
    'login.microsoft': 'Microsoftで続行',
    'login.or': 'または',
    'login.email': 'メールで続行',
    'login.feature.1': 'エンタープライズゲームアーキテクチャ',
    'login.feature.2': 'プロフェッショナルデザインクラスター',
    'login.feature.3': 'AI搭載メディアパイプライン',
    'login.notice.title': '環境に関する通知',
    'login.notice.desc': 'このサンドボックスではGoogleサインインが制限されています。デベロッパーモードに切り替えます。',
    'booking.title.1': '次の制作プロジェクトを',
    'booking.title.2': '開始する',
    'booking.intro': '私たちは、ゲーム開発, アート＆デザイン, AI搭載ツール को 전문으로 하는 다학문 생산 스튜디오입니다.',
    'booking.partner': 'デモではなく、実制作に対応した結果を必要とするスタジオ, ブランド, チームのためのアウトソーシングパートナーとして活動しています。',
    'booking.services.title': '私たちのサービス',
    'booking.service.1.title': '🎮 ゲーム開発',
    'booking.service.1.desc': 'モバイル、PC、Web向けのフルサイクルゲーム開発。プロトタイプから製品版ビルドまで対応。',
    'booking.service.2.title': '🎨 アート＆デザイン',
    'booking.service.2.desc': '高品質なゲームアート, UI/UX, イラスト, ブランディング, 実制作向けのシネマティックビジュアル。',
    'booking.service.3.title': '🤖 AIツール＆自動化',
    'booking.service.3.desc': 'コンテンツ制作を加速し、ワークフローを自動化し、内部制作システムをサポートするカスタムAIツール. ',
    'booking.process.title': '私たちの進め方',
    'booking.process.1': '発見と範囲 — 目標、要件、タイムライン、制作上の制約を調整します。',
    'booking.process.2': '制作と反復 — 高速なフィードバックサイクルを持つ拡張チームとして機能します。',
    'booking.process.3': '納品とサポート — 即戦力となるアセット, システム, および納品後のサポート。',
    'booking.footer.tags': '🌍 グローバルチーム · リモート対応 · NDA対応 · 制作第一',
    'booking.form.title': 'プロジェクトのお問い合わせ',
    'booking.form.subtitle': 'プロジェクトについてお聞かせください。48時間以内に検討し、ご連絡いたします。',
    'booking.form.name': '氏名',
    'booking.form.company': '会社名 / スタジオ名',
    'booking.form.email': 'ビジネスメール',
    'booking.form.type': 'プロジェクトの種類',
    'booking.form.industry': '業界',
    'booking.form.budget': '推定予算',
    'booking.form.timeline': '目標タイムライン',
    'booking.form.desc': 'プロジェクト、範囲, タイムライン, およびアウトソーシングしたい内容について説明してください。',
    'booking.form.submit': 'プロジェクトの相談を開始 →',
    'booking.form.footer': '私たちはデータを尊重します。ご要望に応じてNDAを締結した上での協議も可能です。',
    'market.filter.all': 'すべて',
    'market.filter.games': 'ゲーム',
    'market.filter.design': 'アート＆デザイン',
    'market.filter.tools': 'AIツール',
    'market.filter.cases': '事例研究',
    'market.filter.secondary_all': 'すべての{0}',
    'market.placeholder.all': 'サービス、ソリューション、事例研究を探索…',
    'market.placeholder.games': 'ゲーム開発サービスを探索…',
    'market.placeholder.design': 'アート＆デザイン制作を探索…',
    'market.placeholder.tools': 'AIビデオ、画像、自動化ツールを探索…',
    'market.placeholder.cases': '実際の制作事例を探索…',
    'market.search.directive.1': '市場、ユースケース、またはソリューションで検索…',
    'market.search.directive.2': '業界別のリアルなAI活用事例を探索',
    'market.search.directive.3': '実稼働中のAIソリューションを見つける',
    'market.search.directive.4': '実ビジネス向けに構築されたワークフローを発見',
    'market.search.directive.5': '今日解決したい課題は何ですか？',
    'market.search.directive.6': '実績のあるAIユースケースを閲覧',
    'market.search.placeholder': 'AI製品、アプリ、システムを検索...',
    'market.search.no_matches': '一致する結果はありません',
    'market.search.retry': 'システムパラメータを調整して、再試行してください。',
    'market.search.reset': 'システム検索のリセット',
    'market.status.verified': '検証済みAIシステム',
    'market.status.operational': '稼働中',
    'market.node.active': 'ノード_アクティブ',
    'market.btn.specs': '仕様を初期化',
    'card.btn': '探索',
  }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [lang, setLang] = useState<Language>(() => {
    const saved = localStorage.getItem('skyversis_lang');
    return (saved as Language) || 'en';
  });

  useEffect(() => {
    const detected = localStorage.getItem('skyverses_lang_detected');
    
    // Chỉ auto-detect nếu chưa từng detect (lần đầu truy cập hoặc user cũ chưa có flag)
    if (detected) return;
    
    localStorage.setItem('skyverses_lang_detected', '1');
    
    fetch('https://ipapi.co/json/')
      .then(res => res.json())
      .then(data => {
        const country = data.country_code;
        const mapping: Record<string, Language> = { 
          'VN': 'vi', 
          'KR': 'ko', 
          'JP': 'ja' 
        };
        const detectedLang = mapping[country] || 'en';
        setLang(detectedLang);
        localStorage.setItem('skyversis_lang', detectedLang);
      })
      .catch(() => {
        const browserLang = navigator.language.split('-')[0];
        const fallback = (['vi', 'ko', 'ja'].includes(browserLang) ? browserLang : 'en') as Language;
        setLang(fallback);
        localStorage.setItem('skyversis_lang', fallback);
      });
  }, []);

  useEffect(() => {
    localStorage.setItem('skyversis_lang', lang);
  }, [lang]);

  const t = (key: string) => {
    return translations[lang][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ lang, setLang, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) throw new Error('useLanguage must be used within LanguageProvider');
  return context;
};
