
import React from 'react';
import {
  Sparkles, Edit3, Bot, LayoutGrid, Download, Image,
} from 'lucide-react';
import {
  FadeInUp, StaggerChildren, SectionLabel, HoverCard,
} from '../_shared/SectionAnimations';

// CDN URLs — generated by scripts/gen_aislide_landing_images.sh
const CDN_features_ai_content   = 'https://imagedelivery.net/eCWooK4EUyalJ6a-Nut5cw/4ef2f077-f563-447e-a0e3-b4d4191fc800/public';
const CDN_features_ai_bg        = 'https://imagedelivery.net/eCWooK4EUyalJ6a-Nut5cw/6d25a1ba-9472-4ad3-9aec-b53dfa45ac00/public';
const CDN_features_live_edit    = 'https://imagedelivery.net/eCWooK4EUyalJ6a-Nut5cw/6d75f4a5-b27a-4a32-2930-5864796d3f00/public';
const CDN_features_ai_suggest   = 'https://imagedelivery.net/eCWooK4EUyalJ6a-Nut5cw/671d4897-71f2-4436-8052-a0aefcce3900/public';
const CDN_features_5_layouts    = 'https://imagedelivery.net/eCWooK4EUyalJ6a-Nut5cw/5af65c10-9db3-4227-1d29-328e39064e00/public';
const CDN_features_export       = 'https://imagedelivery.net/eCWooK4EUyalJ6a-Nut5cw/25ef48c1-1b8e-405a-30b5-235cc3b6eb00/public';

const FEATURES = [
  {
    icon: Sparkles,
    title: 'AI sinh nội dung thông minh',
    desc: 'Nhập chủ đề → AI viết outline + nội dung từng slide ngay lập tức, nhất quán style và ngôn ngữ toàn bộ deck.',
    featured: true,
    thumbUrl: CDN_features_ai_content,
  },
  {
    icon: Image,
    title: 'Ảnh nền AI riêng mỗi slide',
    desc: 'Mỗi slide được gen 1 ảnh background độc đáo, đúng tone topic và phong cách bạn chọn. Hoàn toàn tự động.',
    featured: true,
    thumbUrl: CDN_features_ai_bg,
  },
  {
    icon: Edit3,
    title: 'Live editor trực tiếp',
    desc: 'Click vào text bất kỳ để chỉnh ngay trên canvas. Không cần mở tool khác.',
    featured: false,
    thumbUrl: CDN_features_live_edit,
  },
  {
    icon: Bot,
    title: 'AI Suggest per slide',
    desc: '3 gợi ý nội dung thay thế cho mỗi slide. 1 click để áp dụng ngay.',
    featured: false,
    thumbUrl: CDN_features_ai_suggest,
  },
  {
    icon: LayoutGrid,
    title: '5 Layout templates',
    desc: 'title-center, title-left, two-col, full-bg, image-right. Đổi layout 1 click.',
    featured: false,
    thumbUrl: CDN_features_5_layouts,
  },
  {
    icon: Download,
    title: 'Export đa định dạng',
    desc: 'Xuất PPTX (PowerPoint), PDF, hoặc PNG từng slide. Dùng được ngay.',
    featured: false,
    thumbUrl: CDN_features_export,
  },
];

export const FeaturesSection: React.FC = () => (
  <section className="py-20 px-6 bg-black/[0.01] dark:bg-white/[0.01]">
    <div className="max-w-[1400px] mx-auto">
      <FadeInUp className="text-center mb-14">
        <SectionLabel>TÍNH NĂNG</SectionLabel>
        <h2 className="text-3xl md:text-4xl font-black text-slate-900 dark:text-white mb-3">
          Tất cả trong một workspace
        </h2>
        <p className="text-base text-slate-500 dark:text-white/40 max-w-lg mx-auto">
          Từ AI tạo nội dung, gen ảnh nền, live edit, đến export — không cần rời khỏi trang.
        </p>
      </FadeInUp>

      <StaggerChildren
        className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4"
        staggerDelay={0.07}
      >
        {FEATURES.map(f => {
          const Icon = f.icon;
          return (
            <HoverCard
              key={f.title}
              className={`overflow-hidden bg-white dark:bg-[#111] ${f.featured ? 'md:col-span-1 ring-1 ring-brand-blue/20' : ''}`}
            >
              {/* Thumbnail image (CDN) */}
              {f.thumbUrl ? (
                <div className="relative h-28 overflow-hidden">
                  <img
                    src={f.thumbUrl}
                    alt={f.title}
                    loading="lazy"
                    className="w-full h-full object-cover"
                  />
                  <div className="absolute inset-0 bg-gradient-to-b from-transparent to-black/40" />
                  {f.featured && (
                    <div className="absolute top-2 left-2 inline-flex items-center gap-1 px-2 py-0.5 rounded-full bg-brand-blue text-white text-[8px] font-bold border border-brand-blue/40">
                      <Sparkles size={7} />
                      Nổi bật
                    </div>
                  )}
                </div>
              ) : (
                /* Fallback if image not yet generated */
                f.featured && (
                  <div className="px-5 pt-5">
                    <div className="inline-flex items-center gap-1 px-2 py-0.5 rounded-full bg-brand-blue/[0.08] text-brand-blue text-[8px] font-bold mb-1 border border-brand-blue/20">
                      <Sparkles size={7} />
                      Nổi bật
                    </div>
                  </div>
                )
              )}

              <div className="p-5">
                <div className={`w-9 h-9 rounded-xl bg-brand-blue/10 text-brand-blue flex items-center justify-center mb-3`}>
                  <Icon size={17} />
                </div>
                <h3 className="text-sm font-bold text-slate-800 dark:text-white mb-2">{f.title}</h3>
                <p className="text-[12px] text-slate-500 dark:text-white/40 leading-relaxed">{f.desc}</p>
              </div>
            </HoverCard>
          );
        })}
      </StaggerChildren>
    </div>
  </section>
);
