
import React from 'react';
import {
  Briefcase, GraduationCap, TrendingUp,
  Megaphone, Heart, ShoppingBag,
} from 'lucide-react';
import {
  FadeInUp, StaggerChildren, SectionLabel, HoverCard,
} from '../_shared/SectionAnimations';

// CDN URLs — generated by scripts/gen_aislide_landing_images.sh
const CDN_usecase_business    = 'https://imagedelivery.net/eCWooK4EUyalJ6a-Nut5cw/1005dc68-67e5-469b-6d98-c24121de1800/public';
const CDN_usecase_education   = 'https://imagedelivery.net/eCWooK4EUyalJ6a-Nut5cw/ec5a8cc5-c8cc-483d-3b62-39b13d622900/public';
const CDN_usecase_marketing   = 'https://imagedelivery.net/eCWooK4EUyalJ6a-Nut5cw/9ee85825-110f-4ac0-f0a0-18c8a9792a00/public';
const CDN_usecase_startup     = 'https://imagedelivery.net/eCWooK4EUyalJ6a-Nut5cw/6937d44e-f926-45b1-4e10-a24127b20300/public';
const CDN_usecase_healthcare  = 'https://imagedelivery.net/eCWooK4EUyalJ6a-Nut5cw/b6b078e2-6288-42aa-0624-328a0f7b3b00/public';
const CDN_usecase_ecommerce   = 'https://imagedelivery.net/eCWooK4EUyalJ6a-Nut5cw/3f1fceda-330a-49c0-72e8-ab024e22ad00/public';

interface UseCase {
  icon: React.ElementType;
  title: string;
  desc: string;
  tag: string;
  color: string;
  bg: string;
  dot: string;
  imgUrl: string;
  useCases: string[];
}

const USE_CASES: UseCase[] = [
  {
    icon: Briefcase,
    title: 'Business Pitch',
    desc: 'Tạo investor deck chuyên nghiệp trong 2 phút. AI viết story, gen background cinematic.',
    tag: 'Business',
    color: 'text-brand-blue',
    bg: 'bg-brand-blue/10',
    dot: 'bg-brand-blue/60',
    imgUrl: CDN_usecase_business,
    useCases: ['Investor Pitch Deck', 'Board Presentation', 'Partnership Proposal'],
  },
  {
    icon: GraduationCap,
    title: 'Giáo dục',
    desc: 'Bài giảng, slide học thuật đẹp mắt với cấu trúc nội dung rõ ràng.',
    tag: 'Education',
    color: 'text-violet-500',
    bg: 'bg-violet-500/10',
    dot: 'bg-violet-500/60',
    imgUrl: CDN_usecase_education,
    useCases: ['Bài giảng đại học', 'Seminar & Workshop', 'Luận văn tốt nghiệp'],
  },
  {
    icon: TrendingUp,
    title: 'Business Report',
    desc: 'Báo cáo kinh doanh, KPI quarterly với AI outline nhất quán.',
    tag: 'Corporate',
    color: 'text-emerald-500',
    bg: 'bg-emerald-500/10',
    dot: 'bg-emerald-500/60',
    imgUrl: CDN_usecase_marketing,
    useCases: ['Báo cáo doanh thu Q4', 'OKR Review Deck', 'Team Performance Brief'],
  },
  {
    icon: Megaphone,
    title: 'Marketing Campaign',
    desc: 'Campaign deck vibrant, CTA mạnh, phù hợp pitch cho client.',
    tag: 'Marketing',
    color: 'text-amber-500',
    bg: 'bg-amber-500/10',
    dot: 'bg-amber-500/60',
    imgUrl: CDN_usecase_startup,
    useCases: ['Client Campaign Deck', 'Brand Strategy Slides', 'Campaign Post-mortem'],
  },
  {
    icon: Heart,
    title: 'Healthcare',
    desc: 'Medical briefing, conference slide chuẩn chỉnh, phong cách minimal sạch.',
    tag: 'Healthcare',
    color: 'text-rose-500',
    bg: 'bg-rose-500/10',
    dot: 'bg-rose-500/60',
    imgUrl: CDN_usecase_healthcare,
    useCases: ['Medical Conference', 'Patient Education', 'Clinical Research Brief'],
  },
  {
    icon: ShoppingBag,
    title: 'Product Launch',
    desc: 'Launch deck showcase sản phẩm mới với visual AI ấn tượng.',
    tag: 'E-commerce',
    color: 'text-cyan-500',
    bg: 'bg-cyan-500/10',
    dot: 'bg-cyan-500/60',
    imgUrl: CDN_usecase_ecommerce,
    useCases: ['New Product Launch', 'Retailer Pitch', 'E-commerce Campaign'],
  },
];

export const UseCasesSection: React.FC = () => (
  <section className="py-20 px-6 border-t border-black/[0.06] dark:border-white/[0.04]">
    <div className="max-w-[1400px] mx-auto">
      <FadeInUp className="text-center mb-14">
        <SectionLabel>ỨNG DỤNG THỰC TẾ</SectionLabel>
        <h2 className="text-3xl md:text-4xl font-black text-slate-900 dark:text-white mb-3">
          Phù hợp với mọi ngành nghề
        </h2>
        <p className="text-base text-slate-500 dark:text-white/40 max-w-lg mx-auto">
          Từ startup đến giáo dục, từ marketing đến y tế — AI Slide Creator đều xử lý được.
        </p>
      </FadeInUp>

      <StaggerChildren
        className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4"
        staggerDelay={0.07}
      >
        {USE_CASES.map(uc => {
          const Icon = uc.icon;
          return (
            <HoverCard key={uc.title} className="overflow-hidden bg-white dark:bg-[#111]">
              {/* CDN image thumbnail */}
              <div className="relative h-32 overflow-hidden">
                <img
                  src={uc.imgUrl}
                  alt={uc.title}
                  loading="lazy"
                  className="w-full h-full object-cover"
                />
                <div className="absolute inset-0 bg-gradient-to-b from-transparent to-black/60" />
                {/* Overlay tag */}
                <span className={`absolute top-2 right-2 px-2 py-0.5 rounded-full text-[8px] font-bold bg-black/40 backdrop-blur-sm ${uc.color} border border-current/20`}>
                  {uc.tag}
                </span>
              </div>

              <div className="p-5">
                {/* Icon */}
                <div className={`w-10 h-10 rounded-xl ${uc.bg} ${uc.color} flex items-center justify-center mb-3`}>
                  <Icon size={18} />
                </div>

                {/* Title + desc */}
                <h3 className="text-sm font-bold text-slate-800 dark:text-white mb-1.5">{uc.title}</h3>
                <p className="text-[11px] text-slate-500 dark:text-white/40 leading-relaxed mb-4">{uc.desc}</p>

                {/* Use case list */}
                <div className="space-y-1.5 pt-3 border-t border-black/[0.04] dark:border-white/[0.04]">
                  {uc.useCases.map((item, i) => (
                    <div key={i} className="flex items-center gap-2">
                      <div className={`w-1.5 h-1.5 rounded-full shrink-0 ${uc.dot}`} />
                      <p className="text-[11px] text-slate-600 dark:text-white/50 font-medium">{item}</p>
                    </div>
                  ))}
                </div>
              </div>
            </HoverCard>
          );
        })}
      </StaggerChildren>
    </div>
  </section>
);


interface UseCase {
  icon: React.ElementType;
  title: string;
  desc: string;
  tag: string;
  color: string;
  bg: string;
  dot: string;
  useCases: string[];
}

const USE_CASES: UseCase[] = [
  {
    icon: Briefcase,
    title: 'Business Pitch',
    desc: 'Tạo investor deck chuyên nghiệp trong 2 phút. AI viết story, gen background cinematic.',
    tag: 'Business',
    color: 'text-brand-blue',
    bg: 'bg-brand-blue/10',
    dot: 'bg-brand-blue/60',
    useCases: ['Investor Pitch Deck', 'Board Presentation', 'Partnership Proposal'],
  },
  {
    icon: GraduationCap,
    title: 'Giáo dục',
    desc: 'Bài giảng, slide học thuật đẹp mắt với cấu trúc nội dung rõ ràng.',
    tag: 'Education',
    color: 'text-violet-500',
    bg: 'bg-violet-500/10',
    dot: 'bg-violet-500/60',
    useCases: ['Bài giảng đại học', 'Seminar & Workshop', 'Luận văn tốt nghiệp'],
  },
  {
    icon: TrendingUp,
    title: 'Business Report',
    desc: 'Báo cáo kinh doanh, KPI quarterly với AI outline nhất quán.',
    tag: 'Corporate',
    color: 'text-emerald-500',
    bg: 'bg-emerald-500/10',
    dot: 'bg-emerald-500/60',
    useCases: ['Báo cáo doanh thu Q4', 'OKR Review Deck', 'Team Performance Brief'],
  },
  {
    icon: Megaphone,
    title: 'Marketing Campaign',
    desc: 'Campaign deck vibrant, CTA mạnh, phù hợp pitch cho client.',
    tag: 'Marketing',
    color: 'text-amber-500',
    bg: 'bg-amber-500/10',
    dot: 'bg-amber-500/60',
    useCases: ['Client Campaign Deck', 'Brand Strategy Slides', 'Campaign Post-mortem'],
  },
  {
    icon: Heart,
    title: 'Healthcare',
    desc: 'Medical briefing, conference slide chuẩn chỉnh, phong cách minimal sạch.',
    tag: 'Healthcare',
    color: 'text-rose-500',
    bg: 'bg-rose-500/10',
    dot: 'bg-rose-500/60',
    useCases: ['Medical Conference', 'Patient Education', 'Clinical Research Brief'],
  },
  {
    icon: ShoppingBag,
    title: 'Product Launch',
    desc: 'Launch deck showcase sản phẩm mới với visual AI ấn tượng.',
    tag: 'E-commerce',
    color: 'text-cyan-500',
    bg: 'bg-cyan-500/10',
    dot: 'bg-cyan-500/60',
    useCases: ['New Product Launch', 'Retailer Pitch', 'E-commerce Campaign'],
  },
];

export const UseCasesSection: React.FC = () => (
  <section className="py-20 px-6 border-t border-black/[0.06] dark:border-white/[0.04]">
    <div className="max-w-[1400px] mx-auto">
      <FadeInUp className="text-center mb-14">
        <SectionLabel>ỨNG DỤNG THỰC TẾ</SectionLabel>
        <h2 className="text-3xl md:text-4xl font-black text-slate-900 dark:text-white mb-3">
          Phù hợp với mọi ngành nghề
        </h2>
        <p className="text-base text-slate-500 dark:text-white/40 max-w-lg mx-auto">
          Từ startup đến giáo dục, từ marketing đến y tế — AI Slide Creator đều xử lý được.
        </p>
      </FadeInUp>

      <StaggerChildren
        className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4"
        staggerDelay={0.07}
      >
        {USE_CASES.map(uc => {
          const Icon = uc.icon;
          return (
            <HoverCard key={uc.title} className="p-5 bg-white dark:bg-[#111]">
              {/* Icon + tag */}
              <div className="flex items-start justify-between mb-3">
                <div className={`w-10 h-10 rounded-xl ${uc.bg} ${uc.color} flex items-center justify-center shrink-0`}>
                  <Icon size={18} />
                </div>
                <span className={`px-2 py-0.5 rounded-full text-[8px] font-bold ${uc.bg} ${uc.color} border border-current/20`}>
                  {uc.tag}
                </span>
              </div>

              {/* Title + desc */}
              <h3 className="text-sm font-bold text-slate-800 dark:text-white mb-1.5">{uc.title}</h3>
              <p className="text-[11px] text-slate-500 dark:text-white/40 leading-relaxed mb-4">{uc.desc}</p>

              {/* Use case list */}
              <div className="space-y-1.5 pt-3 border-t border-black/[0.04] dark:border-white/[0.04]">
                {uc.useCases.map((item, i) => (
                  <div key={i} className="flex items-center gap-2">
                    <div className={`w-1.5 h-1.5 rounded-full shrink-0 ${uc.dot}`} />
                    <p className="text-[11px] text-slate-600 dark:text-white/50 font-medium">{item}</p>
                  </div>
                ))}
              </div>
            </HoverCard>
          );
        })}
      </StaggerChildren>
    </div>
  </section>
);
