import React, { useState } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import { Link } from 'react-router-dom';
import {
  ArrowRight, Zap, Clapperboard, Film, Sparkles,
  ShieldCheck, Play, ChevronRight, Users, Star, Download,
  Camera, Cpu, LayoutGrid, Terminal
} from 'lucide-react';
import StoryboardStudioWorkspace from '../../components/StoryboardStudioWorkspace';
import { usePageMeta } from '../../hooks/usePageMeta';

// ─── CDN IMAGE CONSTANTS ────────────────────────────────────────────────────
// Populated by: bash scripts/gen_storyboard_landing.sh
// AUTO-GENERATED by scripts/gen_storyboard_landing.sh → scripts/storyboard_landing_cdn.sh
const CDN: Record<string, string> = {
  hero_main:                  'https://imagedelivery.net/eCWooK4EUyalJ6a-Nut5cw/f7802461-e33c-4b00-9a69-2beeee3fbb00/public',
  feat_script_split:          'https://imagedelivery.net/eCWooK4EUyalJ6a-Nut5cw/b69caa6a-9c1f-461f-a992-6a588f1e9300/public',
  feat_char_lock:             'https://imagedelivery.net/eCWooK4EUyalJ6a-Nut5cw/4435dcfe-2fd1-4181-1c82-3ff81bc1e400/public',
  feat_batch_image:           'https://imagedelivery.net/eCWooK4EUyalJ6a-Nut5cw/9727b938-20f9-46f8-0a94-be2279ad6600/public',
  feat_video_render:          'https://imagedelivery.net/eCWooK4EUyalJ6a-Nut5cw/6c8a39e7-0f1c-4dd8-817c-41c0458a4800/public',
  feat_timeline:              'https://imagedelivery.net/eCWooK4EUyalJ6a-Nut5cw/0a32c07f-96c2-40dd-9345-268764382400/public',
  feat_export:                'https://imagedelivery.net/eCWooK4EUyalJ6a-Nut5cw/4e41e923-0a68-4420-a855-d3557c390400/public',
  step_script_input:          'https://imagedelivery.net/eCWooK4EUyalJ6a-Nut5cw/7dfb06a9-1757-4d64-efaf-44f828588c00/public',
  step_scene_split:           'https://imagedelivery.net/eCWooK4EUyalJ6a-Nut5cw/d8887806-9f21-4ec0-b34d-d094ce4e2100/public',
  step_generate_assets:       'https://imagedelivery.net/eCWooK4EUyalJ6a-Nut5cw/f4fb519b-0229-4966-89f6-e83529e6d200/public',
  step_export_download:       'https://imagedelivery.net/eCWooK4EUyalJ6a-Nut5cw/589ac2cd-5ce8-48d0-2125-c18b1e86ac00/public',
  usecase_tvc:                'https://imagedelivery.net/eCWooK4EUyalJ6a-Nut5cw/4f6c81d8-4c67-4131-eb9d-9c18e639cb00/public',
  usecase_mv:                 'https://imagedelivery.net/eCWooK4EUyalJ6a-Nut5cw/1187c21b-4e25-4ca7-8bc4-9efd7b9ddd00/public',
  usecase_short_film:         'https://imagedelivery.net/eCWooK4EUyalJ6a-Nut5cw/b13168cc-cb53-4129-667d-64b09b9c5700/public',
  usecase_game_cutscene:      'https://imagedelivery.net/eCWooK4EUyalJ6a-Nut5cw/415be258-4792-4fcd-524d-45cf475d9500/public',
  usecase_education:          'https://imagedelivery.net/eCWooK4EUyalJ6a-Nut5cw/b0e4adca-d433-40e8-dc23-6a32c0a1b200/public',
  usecase_virtual_influencer: 'https://imagedelivery.net/eCWooK4EUyalJ6a-Nut5cw/25c62379-20f9-4e8b-01d7-53a546100900/public',
  scene_demo_landscape:       'https://imagedelivery.net/eCWooK4EUyalJ6a-Nut5cw/10924373-b021-49c6-3f1b-ddefd7f75500/public',
  scene_demo_portrait:        'https://imagedelivery.net/eCWooK4EUyalJ6a-Nut5cw/71cb7ec3-b4ba-4835-39c3-a41132b6fb00/public',
  scene_demo_action:          'https://imagedelivery.net/eCWooK4EUyalJ6a-Nut5cw/06585f6d-0382-4ac6-7d47-8920291b3700/public',
};

// ─── DATA ───────────────────────────────────────────────────────────────────
const FEATURES = [
  {
    key: 'feat_script_split',
    icon: <Terminal size={20} />,
    title: 'Phân tách kịch bản AI',
    desc: 'Hệ thống phân tích ngữ nghĩa tự động bóc tách kịch bản thô thành các phân cảnh quay chi tiết, nhất quán và sẵn sàng để render trong tích tắc.',
    accent: 'brand-blue',
  },
  {
    key: 'feat_char_lock',
    icon: <Users size={20} />,
    title: 'Visual Anchoring nhân vật',
    desc: 'Công nghệ neo danh tính hình ảnh giữ cho nhân vật hoàn toàn nhất quán 100% qua mọi phân cảnh — không biến dạng, không trôi tạo hình.',
    accent: 'purple-500',
  },
  {
    key: 'feat_batch_image',
    icon: <LayoutGrid size={20} />,
    title: 'Tạo ảnh hàng loạt',
    desc: 'Render đồng thời toàn bộ phân cảnh trên hạ tầng AI phân tán. Hàng chục cảnh quay hoàn chỉnh trong thời gian mà người thường mất cho một cảnh.',
    accent: 'rose-500',
  },
  {
    key: 'feat_video_render',
    icon: <Film size={20} />,
    title: 'Kết xuất video AI',
    desc: 'Chuyển đổi từng phân cảnh tĩnh thành video cinematic chuyển động mượt mà bằng các mô hình AI thế hệ mới nhất: VEO 3, Kling, Wan 2.1.',
    accent: 'amber-500',
  },
  {
    key: 'feat_timeline',
    icon: <Camera size={20} />,
    title: 'Timeline trực quan',
    desc: 'Giao diện storyboard trực quan cho phép chỉnh sửa prompt, timeline, thứ tự cảnh quay và điều phối toàn bộ quá trình sản xuất một cách dễ dàng.',
    accent: 'emerald-500',
  },
  {
    key: 'feat_export',
    icon: <Download size={20} />,
    title: 'Export & Pipeline',
    desc: 'Xuất toàn bộ dự án dưới dạng ảnh HD, video MP4, hoặc storyboard PDF. Tự động upload lên CDN sẵn sàng phân phối ngay lập tức.',
    accent: 'cyan-500',
  },
];

const WORKFLOW_STEPS = [
  {
    key: 'step_script_input',
    num: '01',
    title: 'Nhập kịch bản',
    desc: 'Dán ý tưởng kịch bản thuần văn bản — từ vài dòng đến cả chương. Tải kèm ảnh reference nhân vật và audio nếu cần.',
  },
  {
    key: 'step_scene_split',
    num: '02',
    title: 'AI phân tách cảnh',
    desc: 'AI phân tích ngữ nghĩa và tự động chia kịch bản thành các phân cảnh quay độc lập với mô tả chi tiết, thời lượng và hướng camera.',
  },
  {
    key: 'step_generate_assets',
    num: '03',
    title: 'Tạo ảnh & video',
    desc: 'Render đồng loạt toàn bộ phân cảnh — ảnh panoramic hoặc video chuyển động — theo aesthetic profile đã cài đặt.',
  },
  {
    key: 'step_export_download',
    num: '04',
    title: 'Xuất & phân phối',
    desc: 'Download từng cảnh hoặc toàn bộ dự án. Export thành storyboard PDF hoặc video hoàn chỉnh sẵn sàng phát hành.',
  },
];

const USE_CASES = [
  { key: 'usecase_tvc',                title: 'TVC Quảng cáo', tag: 'Commercial' },
  { key: 'usecase_mv',                 title: 'MV Ca nhạc AI', tag: 'Music Video' },
  { key: 'usecase_short_film',         title: 'Phim ngắn & Storytelling', tag: 'Short Film' },
  { key: 'usecase_game_cutscene',      title: 'Game Cutscenes', tag: 'Gaming' },
  { key: 'usecase_education',          title: 'Video Giáo dục', tag: 'Education' },
  { key: 'usecase_virtual_influencer', title: 'Virtual Influencers', tag: 'Creator' },
];

const SCENE_DEMOS = [
  { key: 'scene_demo_landscape', order: '01', type: 'Cảnh mở', prompt: 'Aerial establishing shot of coastal Vietnamese city at golden hour. Camera slowly descends toward waterfront district.' },
  { key: 'scene_demo_portrait',  order: '02', type: 'Nhân vật', prompt: 'Close-up character portrait, natural window sidelight, shallow DOF. Slight hesitation before speaking.' },
  { key: 'scene_demo_action',    order: '03', type: 'Hành động', prompt: 'Dynamic chase sequence through neon-lit wet alleyway at night. Low-angle tracking shot, rain splashing.' },
];

// ─── COMPONENT ───────────────────────────────────────────────────────────────
const StoryboardStudioPage: React.FC = () => {
  usePageMeta({
    title: 'Storyboard Studio AI — Phân Cảnh & Tạo Video Kịch Bản Tự Động | Skyverses',
    description: 'Công cụ AI phân tách kịch bản thành storyboard trực quan, tạo hình và video từng phân cảnh tự động. Hỗ trợ VEO 3, Kling, Wan 2.1. Bảo mật tuyệt đối.',
    keywords: 'storyboard AI, tạo video từ kịch bản, phân cảnh tự động, sản xuất video AI, video script AI, storyboard studio, tạo phim AI',
    canonical: '/product/storyboard-studio',
  });

  const [isStudioOpen, setIsStudioOpen] = useState(false);

  if (isStudioOpen) {
    return (
      <div className="fixed inset-0 z-[500] bg-white dark:bg-black animate-in fade-in duration-300">
        <StoryboardStudioWorkspace onClose={() => setIsStudioOpen(false)} />
      </div>
    );
  }

  return (
    <div className="bg-[#fafafa] dark:bg-[#030304] min-h-screen text-slate-900 dark:text-white font-sans overflow-x-hidden pt-20 transition-colors duration-500">

      {/* ══════════════════════════════════════════════════════
          §1 HERO — split layout, CDN hero image
      ══════════════════════════════════════════════════════ */}
      <section aria-label="Hero" className="relative min-h-[92vh] flex items-center overflow-hidden px-6 lg:px-16 py-24">
        {/* Background glow */}
        <div className="absolute top-0 right-0 w-[900px] h-[700px] bg-brand-blue/5 dark:bg-brand-blue/8 rounded-full blur-[200px] pointer-events-none" />
        <div className="absolute bottom-0 left-0 w-[600px] h-[500px] bg-purple-500/4 rounded-full blur-[180px] pointer-events-none" />

        <div className="max-w-[1440px] mx-auto grid grid-cols-1 lg:grid-cols-2 gap-16 lg:gap-24 items-center relative z-10 w-full">
          {/* Left — copy */}
          <div className="space-y-10 order-2 lg:order-1">
            <motion.div
              initial={{ opacity: 0, y: -12 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: 0.5 }}
              className="inline-flex items-center gap-2.5 px-4 py-1.5 rounded-full bg-brand-blue/10 border border-brand-blue/20 text-brand-blue text-[10px] font-black uppercase tracking-[0.25em]"
            >
              <Clapperboard size={13} /> AI Script-to-Screen Engine
            </motion.div>

            <div className="space-y-6">
              <motion.h1
                initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: 0.5, delay: 0.1 }}
                className="text-5xl lg:text-[80px] xl:text-[96px] font-black leading-[0.88] tracking-tighter text-slate-900 dark:text-white"
              >
                Biến Kịch Bản<br />
                Thành <span className="text-brand-blue italic">Điện Ảnh</span><br />
                Với AI.
              </motion.h1>

              <motion.p
                initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: 0.5, delay: 0.2 }}
                className="text-lg lg:text-xl text-slate-500 dark:text-gray-400 font-medium leading-relaxed max-w-lg border-l-4 border-brand-blue pl-6"
              >
                Phân tách kịch bản thô thành storyboard trực quan, tạo ảnh và video từng phân cảnh tự động. Công cụ sản xuất video AI chuyên nghiệp đầu tiên tại Việt Nam.
              </motion.p>
            </div>

            <motion.div
              initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: 0.5, delay: 0.3 }}
              className="flex flex-col sm:flex-row gap-4"
            >
              <button
                id="btn-launch-studio-hero"
                onClick={() => setIsStudioOpen(true)}
                className="group inline-flex items-center justify-center gap-3 bg-brand-blue text-white px-10 py-5 rounded-xl text-xs font-black uppercase tracking-[0.3em] shadow-[0_20px_60px_rgba(0,144,255,0.35)] hover:scale-105 active:scale-95 transition-all"
              >
                <Zap size={16} fill="currentColor" />
                Khởi chạy Studio Pro
                <ArrowRight size={16} className="group-hover:translate-x-1 transition-transform" />
              </button>
              <button
                onClick={() => document.getElementById('how-it-works')?.scrollIntoView({ behavior: 'smooth' })}
                className="inline-flex items-center justify-center gap-3 px-10 py-5 border border-slate-200 dark:border-white/10 rounded-xl text-xs font-black uppercase tracking-[0.3em] text-slate-600 dark:text-white hover:bg-slate-50 dark:hover:bg-white/5 transition-all"
              >
                <Play size={14} fill="currentColor" /> Xem cách hoạt động
              </button>
            </motion.div>

            {/* Stats bar */}
            <motion.div
              initial={{ opacity: 0 }} animate={{ opacity: 1 }} transition={{ delay: 0.5 }}
              className="flex items-center gap-10 pt-4 border-t border-slate-100 dark:border-white/5"
            >
              {[
                { val: 'VEO 3', label: 'Video Engine' },
                { val: '4K', label: 'Max Resolution' },
                { val: '∞', label: 'Phân cảnh / Dự án' },
                { val: '100%', label: 'Nhất quán nhân vật' },
              ].map((s) => (
                <div key={s.label} className="flex flex-col">
                  <span className="text-2xl font-black italic text-brand-blue leading-none">{s.val}</span>
                  <span className="text-[9px] font-black uppercase text-slate-400 dark:text-gray-500 tracking-widest mt-1">{s.label}</span>
                </div>
              ))}
            </motion.div>
          </div>

          {/* Right — CDN hero image */}
          <motion.div
            initial={{ opacity: 0, scale: 0.96 }} animate={{ opacity: 1, scale: 1 }} transition={{ duration: 0.7, delay: 0.1 }}
            className="order-1 lg:order-2 relative"
          >
            <div className="relative rounded-[2.5rem] overflow-hidden shadow-[0_40px_120px_rgba(0,0,0,0.2)] border border-slate-200/60 dark:border-white/5 aspect-[16/10]">
              <img
                src={CDN.hero_main}
                alt="Storyboard Studio AI — Phân cảnh kịch bản điện ảnh với AI"
                className="w-full h-full object-cover"
                loading="eager"
              />
              <div className="absolute inset-0 bg-gradient-to-t from-black/20 to-transparent" />
              {/* Floating badge */}
              <div className="absolute bottom-6 left-6 flex items-center gap-3 bg-white/10 dark:bg-black/40 backdrop-blur-xl border border-white/20 rounded-2xl px-5 py-3">
                <div className="w-2 h-2 rounded-full bg-emerald-400 animate-pulse" />
                <span className="text-[10px] font-black uppercase tracking-widest text-white">Studio Engine Active</span>
              </div>
            </div>
            {/* Decorative glow ring */}
            <div className="absolute -inset-4 -z-10 bg-brand-blue/10 rounded-[3rem] blur-2xl" />
          </motion.div>
        </div>
      </section>

      {/* ══════════════════════════════════════════════════════
          §2 FEATURES GRID — 6 CDN image cards
      ══════════════════════════════════════════════════════ */}
      <section aria-label="Tính năng" className="py-32 lg:py-40 bg-slate-50 dark:bg-[#06060a] border-y border-slate-100 dark:border-white/5 transition-colors">
        <div className="max-w-7xl mx-auto px-6 lg:px-12">
          <div className="text-center space-y-4 mb-20">
            <p className="text-brand-blue text-[10px] font-black uppercase tracking-[0.5em]">Kiến trúc sản xuất AI</p>
            <h2 className="text-4xl lg:text-6xl font-black tracking-tighter text-slate-900 dark:text-white">
              Mọi công đoạn. Hoàn toàn tự động.
            </h2>
            <p className="text-slate-500 dark:text-gray-400 text-lg max-w-2xl mx-auto leading-relaxed">
              Từ kịch bản thô đến video hoàn chỉnh — Storyboard Studio xử lý toàn bộ pipeline sản xuất với độ chính xác cấp chuyên nghiệp.
            </p>
          </div>

          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6 lg:gap-8">
            {FEATURES.map((f, i) => (
              <motion.article
                key={f.key}
                initial={{ opacity: 0, y: 30 }}
                whileInView={{ opacity: 1, y: 0 }}
                viewport={{ once: true }}
                transition={{ duration: 0.4, delay: i * 0.08 }}
                className="group bg-white dark:bg-[#0c0c10] rounded-2xl overflow-hidden border border-slate-100 dark:border-white/5 hover:border-brand-blue/20 hover:shadow-xl dark:hover:shadow-brand-blue/5 transition-all duration-500 flex flex-col"
              >
                {/* CDN Image */}
                <div className="aspect-[16/9] overflow-hidden bg-slate-100 dark:bg-black relative">
                  <img
                    src={CDN[f.key as keyof typeof CDN]}
                    alt={f.title}
                    className="w-full h-full object-cover group-hover:scale-105 transition-transform duration-700"
                    loading="lazy"
                  />
                  <div className="absolute inset-0 bg-gradient-to-t from-black/30 to-transparent opacity-0 group-hover:opacity-100 transition-opacity duration-500" />
                </div>
                {/* Content */}
                <div className="p-7 flex-grow flex flex-col gap-4">
                  <div className={`w-10 h-10 rounded-xl bg-${f.accent}/10 flex items-center justify-center text-${f.accent} border border-${f.accent}/10`}>
                    {f.icon}
                  </div>
                  <div className="space-y-2 flex-grow">
                    <h3 className="text-lg font-black tracking-tight text-slate-900 dark:text-white">{f.title}</h3>
                    <p className="text-sm text-slate-500 dark:text-gray-400 leading-relaxed">{f.desc}</p>
                  </div>
                </div>
              </motion.article>
            ))}
          </div>
        </div>
      </section>

      {/* ══════════════════════════════════════════════════════
          §3 HOW IT WORKS — 4-step workflow
      ══════════════════════════════════════════════════════ */}
      <section id="how-it-works" aria-label="Quy trình 4 bước" className="py-32 lg:py-40 bg-white dark:bg-[#030304] transition-colors">
        <div className="max-w-7xl mx-auto px-6 lg:px-12">
          <div className="text-center space-y-4 mb-24">
            <p className="text-brand-blue text-[10px] font-black uppercase tracking-[0.5em]">Quy trình sản xuất</p>
            <h2 className="text-4xl lg:text-6xl font-black tracking-tighter text-slate-900 dark:text-white">
              4 bước từ ý tưởng<br />
              đến <span className="text-brand-blue">thước phim hoàn chỉnh.</span>
            </h2>
          </div>

          <div className="space-y-8 lg:space-y-6">
            {WORKFLOW_STEPS.map((step, i) => (
              <motion.div
                key={step.key}
                initial={{ opacity: 0, x: i % 2 === 0 ? -30 : 30 }}
                whileInView={{ opacity: 1, x: 0 }}
                viewport={{ once: true }}
                transition={{ duration: 0.5 }}
                className={`group grid grid-cols-1 lg:grid-cols-2 gap-8 items-center ${i % 2 !== 0 ? 'lg:flex-row-reverse' : ''}`}
              >
                {/* Image side */}
                <div className={`${i % 2 !== 0 ? 'lg:order-2' : ''} relative rounded-2xl overflow-hidden aspect-[16/9] shadow-2xl border border-slate-100 dark:border-white/5`}>
                  <img
                    src={CDN[step.key as keyof typeof CDN]}
                    alt={step.title}
                    className="w-full h-full object-cover group-hover:scale-105 transition-transform duration-700"
                    loading="lazy"
                  />
                  {/* Step number overlay */}
                  <div className="absolute top-5 left-5 w-12 h-12 rounded-full bg-brand-blue flex items-center justify-center text-white text-xs font-black shadow-lg shadow-brand-blue/40">
                    {step.num}
                  </div>
                </div>
                {/* Text side */}
                <div className={`${i % 2 !== 0 ? 'lg:order-1' : ''} space-y-6 px-0 lg:px-8`}>
                  <div className="space-y-2">
                    <span className="text-brand-blue text-[10px] font-black uppercase tracking-[0.4em]">Bước {step.num}</span>
                    <h3 className="text-3xl lg:text-4xl font-black tracking-tighter text-slate-900 dark:text-white">{step.title}</h3>
                  </div>
                  <p className="text-slate-500 dark:text-gray-400 text-base leading-relaxed max-w-md">{step.desc}</p>
                  <div className="flex items-center gap-2 text-brand-blue text-xs font-black uppercase tracking-wider">
                    <ChevronRight size={16} />
                    <span>{i < 3 ? `Tiếp theo: Bước ${WORKFLOW_STEPS[i + 1]?.num}` : 'Hoàn thành dự án'}</span>
                  </div>
                </div>
              </motion.div>
            ))}
          </div>
        </div>
      </section>

      {/* ══════════════════════════════════════════════════════
          §4 SCENE SHOWCASE — demo scene cards với CDN images
      ══════════════════════════════════════════════════════ */}
      <section aria-label="Scene showcase" className="py-32 lg:py-40 bg-slate-50 dark:bg-[#06060a] border-y border-slate-100 dark:border-white/5 transition-colors">
        <div className="max-w-7xl mx-auto px-6 lg:px-12">
          <div className="flex flex-col lg:flex-row justify-between items-end gap-8 mb-16">
            <div className="space-y-4">
              <p className="text-brand-blue text-[10px] font-black uppercase tracking-[0.5em]">Storyboard Demo</p>
              <h2 className="text-4xl lg:text-6xl font-black tracking-tighter text-slate-900 dark:text-white">
                Từng phân cảnh.<br />
                Hoàn hảo từng frame.
              </h2>
            </div>
            <button
              onClick={() => setIsStudioOpen(true)}
              className="group inline-flex items-center gap-3 bg-brand-blue text-white px-8 py-4 rounded-xl text-xs font-black uppercase tracking-[0.3em] shadow-lg hover:scale-105 active:scale-95 transition-all whitespace-nowrap"
            >
              Dùng thử ngay <ArrowRight size={14} className="group-hover:translate-x-1 transition-transform" />
            </button>
          </div>

          <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
            {SCENE_DEMOS.map((scene, i) => (
              <motion.div
                key={scene.key}
                initial={{ opacity: 0, y: 30 }}
                whileInView={{ opacity: 1, y: 0 }}
                viewport={{ once: true }}
                transition={{ duration: 0.4, delay: i * 0.1 }}
                className="group bg-white dark:bg-[#0c0c10] rounded-2xl overflow-hidden border border-slate-100 dark:border-white/5 hover:border-brand-blue/20 shadow-sm hover:shadow-xl transition-all duration-500"
              >
                {/* Scene image */}
                <div className="relative aspect-[16/9] overflow-hidden bg-slate-100 dark:bg-black">
                  <img
                    src={CDN[scene.key as keyof typeof CDN]}
                    alt={`Phân cảnh ${scene.order} — ${scene.type}`}
                    className="w-full h-full object-cover group-hover:scale-105 transition-transform duration-700"
                    loading="lazy"
                  />
                  <div className="absolute inset-0 bg-gradient-to-t from-black/60 via-transparent to-transparent" />
                  {/* Scene badge */}
                  <div className="absolute top-3 left-3 bg-white/10 backdrop-blur-md border border-white/20 rounded-lg px-3 py-1">
                    <span className="text-[9px] font-black uppercase text-white tracking-widest">Cảnh {scene.order}</span>
                  </div>
                  {/* Type badge */}
                  <div className="absolute top-3 right-3 bg-brand-blue text-white text-[8px] font-black uppercase tracking-wider px-2.5 py-1 rounded-lg">
                    {scene.type}
                  </div>
                </div>
                {/* Card content */}
                <div className="p-5 space-y-3">
                  <p className="text-[10px] font-black uppercase text-slate-400 dark:text-gray-500 tracking-widest">Prompt kịch bản</p>
                  <p className="text-sm text-slate-600 dark:text-gray-300 italic leading-relaxed line-clamp-3">"{scene.prompt}"</p>
                  <div className="flex items-center justify-between pt-2 border-t border-slate-100 dark:border-white/5">
                    <div className="flex items-center gap-1.5">
                      <div className="w-1.5 h-1.5 rounded-full bg-emerald-400" />
                      <span className="text-[9px] font-black uppercase text-emerald-500 tracking-widest">AI Generated</span>
                    </div>
                    <span className="text-[9px] font-black uppercase text-slate-300 dark:text-gray-600 tracking-wider">Storyboard Studio</span>
                  </div>
                </div>
              </motion.div>
            ))}
          </div>
        </div>
      </section>

      {/* ══════════════════════════════════════════════════════
          §5 USE CASES
      ══════════════════════════════════════════════════════ */}
      <section aria-label="Use cases" className="py-32 lg:py-40 bg-white dark:bg-[#030304] transition-colors">
        <div className="max-w-7xl mx-auto px-6 lg:px-12">
          <div className="text-center space-y-4 mb-16">
            <p className="text-brand-blue text-[10px] font-black uppercase tracking-[0.5em]">Ứng dụng thực tế</p>
            <h2 className="text-4xl lg:text-6xl font-black tracking-tighter text-slate-900 dark:text-white">
              Giải pháp cho mọi<br />
              <span className="text-brand-blue">thể loại nội dung.</span>
            </h2>
          </div>

          <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-6">
            {USE_CASES.map((uc, i) => (
              <motion.article
                key={uc.key}
                initial={{ opacity: 0, y: 20 }}
                whileInView={{ opacity: 1, y: 0 }}
                viewport={{ once: true }}
                transition={{ duration: 0.4, delay: i * 0.07 }}
                className="group relative overflow-hidden rounded-2xl border border-slate-100 dark:border-white/5 hover:border-brand-blue/30 transition-all duration-500 cursor-pointer shadow-sm hover:shadow-2xl"
              >
                <div className="aspect-[3/2] overflow-hidden bg-slate-100 dark:bg-black">
                  <img
                    src={CDN[uc.key as keyof typeof CDN]}
                    alt={uc.title}
                    className="w-full h-full object-cover grayscale-[30%] group-hover:grayscale-0 group-hover:scale-110 transition-all duration-700"
                    loading="lazy"
                  />
                  <div className="absolute inset-0 bg-gradient-to-t from-black/80 via-black/20 to-transparent" />
                </div>
                <div className="absolute bottom-0 left-0 right-0 p-6">
                  <span className="text-brand-blue text-[9px] font-black uppercase tracking-widest block mb-1">{uc.tag}</span>
                  <h3 className="text-xl font-black tracking-tight text-white translate-y-1 group-hover:translate-y-0 transition-transform duration-300">
                    {uc.title}
                  </h3>
                </div>
              </motion.article>
            ))}
          </div>
        </div>
      </section>

      {/* ══════════════════════════════════════════════════════
          §6 FINAL CTA
      ══════════════════════════════════════════════════════ */}
      <section aria-label="Call to action" className="py-48 text-center relative overflow-hidden bg-slate-50 dark:bg-[#03030a] border-t border-slate-100 dark:border-white/5 transition-colors">
        <div className="absolute inset-0 pointer-events-none overflow-hidden select-none flex items-center justify-center">
          <span className="text-[320px] font-black text-slate-100 dark:text-white/[0.02] leading-none tracking-tighter italic opacity-60">
            STORY
          </span>
        </div>

        <div className="max-w-3xl mx-auto px-6 space-y-12 relative z-10">
          <div className="space-y-6">
            <h2 className="text-5xl lg:text-8xl font-black tracking-tighter leading-[0.85] text-slate-900 dark:text-white">
              Sẵn sàng tạo<br />
              <span className="text-brand-blue italic">tuyệt phẩm?</span>
            </h2>
            <p className="text-slate-500 dark:text-gray-400 text-lg max-w-lg mx-auto leading-relaxed">
              Hàng nghìn nhà sáng tạo, studio và brand đang dùng Storyboard Studio để sản xuất nội dung video AI nhanh hơn 10x.
            </p>
          </div>

          <div className="flex flex-col items-center gap-6">
            <button
              id="btn-launch-studio-cta"
              onClick={() => setIsStudioOpen(true)}
              className="group inline-flex items-center gap-4 bg-slate-900 dark:bg-white text-white dark:text-slate-900 px-16 py-7 rounded-2xl text-sm font-black uppercase tracking-[0.4em] shadow-[0_30px_80px_rgba(0,0,0,0.25)] hover:scale-105 active:scale-95 transition-all"
            >
              <Clapperboard size={20} />
              Trải nghiệm Studio ngay
              <Zap size={20} fill="currentColor" />
            </button>
            <div className="flex items-center gap-6 text-[10px] font-black uppercase tracking-[0.3em] text-slate-400 dark:text-gray-600">
              <div className="flex items-center gap-2"><ShieldCheck size={14} className="text-emerald-500" /> VEO 3 Engine</div>
              <div className="flex items-center gap-2"><Star size={14} className="text-amber-500" /> 4K Export</div>
              <div className="flex items-center gap-2"><Cpu size={14} className="text-brand-blue" /> Bảo mật tuyệt đối</div>
            </div>
          </div>
        </div>
      </section>

    </div>
  );
};

export default StoryboardStudioPage;
